import type { Compas } from "@/lib/ritmo";
import type { Evento, Tonalidad, Voces } from "@/lib/pentagrama";

/**
 * Las partituras, escritas como datos.
 *
 * Igual que las clases: no hay PDF, no hay imagen y no se baja nada. La pieza
 * es una lista de notas con su figura, y el pentagrama se dibuja de eso — así
 * que la app *sabe* qué está sonando y puede tocarlo, seguirte por MIDI y
 * marcarte dónde vas. Con un PDF nada de eso se puede.
 *
 * **Están transcriptas de memoria y son un pedazo.** Las obras son de dominio
 * público (Bach y Beethoven hace bastante que no cobran), pero la transcripción
 * es nuestra y puede tener errores: sale bien el arranque de las conocidas y se
 * pone dudosa en las voces internas. Por eso cada pieza dice hasta qué compás
 * llega y `revisar` marca lo que hay que chequear con el profe. Es la misma
 * regla que `openQuestions` en las clases: mejor la duda anotada que el invento
 * en silencio.
 */

export interface Pieza {
  slug: string;
  titulo: string;
  compositor: string;
  anio: string;
  compas: Compas;
  tonalidad: Tonalidad;
  /** Negras por minuto para el reproductor. */
  bpm: number;
  /**
   * Qué va en cada pentagrama. Una fila de eventos si la mano tiene una sola
   * voz —que es casi siempre— o una lista de filas si tiene dos.
   */
  derecha: Voces;
  izquierda: Voces;
  /** De 1 a 5, para ordenar la lista por lo que se puede intentar hoy. */
  dificultad: number;
  /** Por qué está acá y qué mirar. */
  sobre: string;
  /** Hasta dónde llega lo transcripto. */
  hasta: string;
  /** Compuesta acá: la obra es del cuaderno, no del dominio público. */
  propia?: boolean;
  /** Lo que habría que chequear. Se muestra al pie, sin culpa. */
  revisar?: string;
  /**
   * El MusicXML del que se importó, si existe, servido desde `public/`. Con él
   * la página ofrece la edición completa (OSMD): todo lo que nuestro modelo
   * todavía no representa — ligaduras, matices, digitación, las voces que el
   * importador deja afuera.
   */
  fuente?: string;
}

/** Atajos para que las piezas se lean como música y no como JSON. */
const n = (midis: number | number[], divide: number, extra: Partial<Evento> = {}): Evento => ({
  midis: Array.isArray(midis) ? midis : [midis],
  divide,
  ...extra,
});
/** Tres en el tiempo de dos, que es el grupo irregular que aparece siempre. */
const TRESILLO = { en: 3, de: 2 } as const;
const silencio = (divide: number, extra: Partial<Evento> = {}): Evento => ({
  midis: [],
  divide,
  ...extra,
});

// Las teclas por nombre, para poder escribir la música leyéndola en vez de
// contar números MIDI. Do central = Do4 = 60.
const Sol2 = 43, Si2 = 47;
const Do3 = 48, Re3 = 50, Mi3 = 52, Sol3 = 55, La3 = 57, Si3 = 59;
const Re2 = 38;
const Do4 = 60, Re4 = 62, Mi4 = 64, Fa4 = 65, Sol4 = 67, La4 = 69, Si4 = 71;
const Do5 = 72, Re5 = 74, Mi5 = 76, Fa5 = 77;
// Las de la vuelta de Joaquín.
const Fa2 = 41, Fa3 = 53;
// Las de las tres llegadas: las notas ajenas que traen los dominantes.
const Res3 = 51, Res4 = 63, Fas4 = 66, Sols4 = 68;

// Las del Claro de luna, en Do♯ menor.
const Fas1 = 30, La1 = 33, Dos2 = 37, Fas2 = 42, La2 = 45, Dos3 = 49;
const Fas3 = 54, Sols3 = 56, Dos4b = 61;

export const PIEZAS: Pieza[] = [
  {
    slug: "oda-a-la-alegria",
    titulo: "Oda a la alegría",
    compositor: "Beethoven",
    anio: "1824",
    compas: { numerador: 4, denominador: 4 },
    tonalidad: { tonica: 0, modo: "mayor" },
    bpm: 100,
    dificultad: 1,
    sobre:
      "Ocho compases, todo por grados conjuntos y sin una sola tecla negra. Es la que se puede tocar hoy: la derecha no se mueve de la posición de cinco dedos y la izquierda son dos acordes que ya sabés armar.",
    hasta: "El tema completo, ocho compases.",
    derecha: [
      // Mi mi fa sol | sol fa mi re | do do re mi | mi. re re
      n(Mi4, 4), n(Mi4, 4), n(Fa4, 4), n(Sol4, 4),
      n(Sol4, 4), n(Fa4, 4), n(Mi4, 4), n(Re4, 4),
      n(Do4, 4), n(Do4, 4), n(Re4, 4), n(Mi4, 4),
      n(Mi4, 4, { puntillo: true }), n(Re4, 8), n(Re4, 2),
      // y otra vez, con el final resuelto en Do
      n(Mi4, 4), n(Mi4, 4), n(Fa4, 4), n(Sol4, 4),
      n(Sol4, 4), n(Fa4, 4), n(Mi4, 4), n(Re4, 4),
      n(Do4, 4), n(Do4, 4), n(Re4, 4), n(Mi4, 4),
      n(Re4, 4, { puntillo: true }), n(Do4, 8), n(Do4, 2),
    ],
    izquierda: [
      n([Do3, Sol3], 1),
      n([Si2, Sol3], 1),
      n([Do3, Sol3], 1),
      n([Sol2, Re3], 1),
      n([Do3, Sol3], 1),
      n([Si2, Sol3], 1),
      n([Do3, Mi3], 1),
      n([Sol2, Re3], 2), n([Do3, Sol3], 2),
    ],
  },

  {
    slug: "oda-a-la-alegria-en-sol",
    fuente: "/fuentes/oda-a-la-alegria-en-sol.mxl",
    titulo: "Oda a la alegría, entera y en Sol",
    compositor: "Beethoven",
    anio: "1824",
    compas: { numerador: 4, denominador: 4 },
    tonalidad: { tonica: 7, modo: "mayor" },
    bpm: 120,
    dificultad: 2,
    sobre:
      "El mismo tema de la otra Oda, pero completo: trae la vuelta del medio que la versión de ocho compases saltea, y está en Sol —con su fa sostenido en la armadura—. La izquierda ya no son dos acordes: son tríadas enteras y unos bajos que caminan solos. Compará las dos y se escucha qué le faltaba a la corta.",
    hasta: "Entera: el tema dos veces, la vuelta del medio y el cierre.",
    revisar:
      "Importada de un MusicXML sin pérdidas, así que las notas son las del archivo. El tempo del archivo dice 140; acá arranca en 120, que para leer alcanza y sobra.",
    derecha: [
      // El tema. En Sol arranca en Si, la tercera — igual que en Do arrancaba en Mi.
      n(Si4, 4), n(Si4, 4), n(Do5, 4), n(Re5, 4),
      n(Re5, 4), n(Do5, 4), n(Si4, 4), n(La4, 4),
      n(Sol4, 4), n(Sol4, 4), n(La4, 4), n(Si4, 4),
      n(Si4, 4, { puntillo: true }), n(La4, 8), n(La4, 2),
      n(Si4, 4), n(Si4, 4), n(Do5, 4), n(Re5, 4),
      n(Re5, 4), n(Do5, 4), n(Si4, 4), n(La4, 4),
      n(Sol4, 4), n(Sol4, 4), n(La4, 4), n(Si4, 4),
      n(La4, 4, { puntillo: true }), n(Sol4, 8), n(Sol4, 2),
      // La vuelta del medio, la que la versión corta no tiene.
      n(La4, 4), n(La4, 4), n(Si4, 4), n(Sol4, 4),
      n(La4, 4), n(Si4, 8), n(Do5, 8), n(Si4, 4), n(Sol4, 4),
      n(La4, 4), n(Si4, 8), n(Do5, 8), n(Si4, 4), n(La4, 4),
      n(Sol4, 4), n(La4, 4), n(Re4, 2),
      // Y el tema por última vez, cerrando en Sol.
      n(Si4, 4), n(Si4, 4), n(Do5, 4), n(Re5, 4),
      n(Re5, 4), n(Do5, 4), n(Si4, 4), n(La4, 4),
      n(Sol4, 4), n(Sol4, 4), n(La4, 4), n(Si4, 4),
      n(La4, 4, { puntillo: true }), n(Sol4, 8), n(Sol4, 2),
      n(Sol4, 1),
    ],
    izquierda: [
      // Tríadas de Sol y de Re con séptima, tenidas.
      n([Sol3, Si3, Re4], 1), n([Fas3, La3, Re4], 1), n([Sol3, Si3, Re4], 1),
      n([Sol3, Si3, Re4], 2), n([Fas3, La3, Re4], 2),
      n([Sol3, Si3, Re4], 1), n([Fas3, La3, Re4], 1), n([Sol3, Si3, Re4], 1),
      n([Fas3, La3, Re4], 2), n([Sol3, Si3, Re4], 2),
      // En la vuelta del medio el bajo baja hasta el Re grave y camina.
      n(Re2, 2), n([Re3, Sol3, Si3], 2),
      n(Re2, 2), n([Re3, Sol3, Si3], 2),
      n(Re2, 2), n([Re3, Sol3, Si3], 2),
      n(Dos3, 2), n([Re3, Fas3, La3], 2),
      n([Sol3, Si3, Re4], 1), n([Fas3, La3, Re4], 1), n([Sol3, Si3, Re4], 1),
      n([Fas3, La3, Re4], 2), n([Sol3, Si3, Re4], 2),
      n([Sol3, Si3, Re4], 1),
    ],
  },

  {
    slug: "preludio-en-do",
    fuente: "/fuentes/preludio-en-do.mxl",
    titulo: "Preludio nº 1 en Do mayor",
    compositor: "Bach",
    anio: "1722",
    compas: { numerador: 4, denominador: 4 },
    tonalidad: { tonica: 0, modo: "mayor" },
    bpm: 72,
    dificultad: 2,
    sobre:
      "Entero, y es exactamente lo que estás estudiando: cada compás es un acorde desarmado nota por nota, y lo único que pasa entre compás y compás es que una o dos notas se mueven. Es el enlace de acordes, escrito. El acorde nunca suena en bloque: el bajo arranca, el tenor entra en la segunda semicorchea —ligado hasta la barra— y recién ahí corre el arpegio.",
    hasta: "El preludio entero como viene en el archivo: treinta y cuatro compases.",
    revisar:
      "Importado de un MusicXML sin pérdidas —la primera versión de esta pieza eran cuatro compases escritos de memoria—. Ojo: el archivo trae 34 compases y la edición estándar tiene 35, así que en algún lado falta o se fundió uno; queda para cotejar. El tenor va en el pentagrama de abajo con el bajo, como en el archivo; con qué mano conviene tocarlo es pregunta para el profe.",
    derecha: [
      silencio(8), n(67, 16), n(72, 16), n(76, 16), n(67, 16), n(72, 16),
      n(76, 16), silencio(8), n(67, 16), n(72, 16), n(76, 16), n(67, 16),
      n(72, 16), n(76, 16), silencio(8), n(69, 16), n(74, 16), n(77, 16),
      n(69, 16), n(74, 16), n(77, 16), silencio(8), n(69, 16), n(74, 16),
      n(77, 16), n(69, 16), n(74, 16), n(77, 16), silencio(8), n(67, 16),
      n(74, 16), n(77, 16), n(67, 16), n(74, 16), n(77, 16), silencio(8),
      n(67, 16), n(74, 16), n(77, 16), n(67, 16), n(74, 16), n(77, 16),
      silencio(8), n(67, 16), n(72, 16), n(76, 16), n(67, 16), n(72, 16),
      n(76, 16), silencio(8), n(67, 16), n(72, 16), n(76, 16), n(67, 16),
      n(72, 16), n(76, 16), silencio(8), n(69, 16), n(76, 16), n(81, 16),
      n(69, 16), n(76, 16), n(81, 16), silencio(8), n(69, 16), n(76, 16),
      n(81, 16), n(69, 16), n(76, 16), n(81, 16), silencio(8), n(66, 16),
      n(69, 16), n(74, 16), n(66, 16), n(69, 16), n(74, 16), silencio(8),
      n(66, 16), n(69, 16), n(74, 16), n(66, 16), n(69, 16), n(74, 16),
      silencio(8), n(67, 16), n(74, 16), n(79, 16), n(67, 16), n(74, 16),
      n(79, 16), silencio(8), n(67, 16), n(74, 16), n(79, 16), n(67, 16),
      n(74, 16), n(79, 16), silencio(8), n(64, 16), n(67, 16), n(72, 16),
      n(64, 16), n(67, 16), n(72, 16), silencio(8), n(64, 16), n(67, 16),
      n(72, 16), n(64, 16), n(67, 16), n(72, 16), silencio(8), n(64, 16),
      n(67, 16), n(72, 16), n(64, 16), n(67, 16), n(72, 16), silencio(8),
      n(64, 16), n(67, 16), n(72, 16), n(64, 16), n(67, 16), n(72, 16),
      silencio(8), n(62, 16), n(66, 16), n(72, 16), n(62, 16), n(66, 16),
      n(72, 16), silencio(8), n(62, 16), n(66, 16), n(72, 16), n(62, 16),
      n(66, 16), n(72, 16), silencio(8), n(62, 16), n(67, 16), n(71, 16),
      n(62, 16), n(67, 16), n(71, 16), silencio(8), n(62, 16), n(67, 16),
      n(71, 16), n(62, 16), n(67, 16), n(71, 16), silencio(8), n(64, 16),
      n(67, 16), n(73, 16), n(64, 16), n(67, 16), n(73, 16), silencio(8),
      n(64, 16), n(67, 16), n(73, 16), n(64, 16), n(67, 16), n(73, 16),
      silencio(8), n(62, 16), n(69, 16), n(74, 16), n(62, 16), n(69, 16),
      n(74, 16), silencio(8), n(62, 16), n(69, 16), n(74, 16), n(62, 16),
      n(69, 16), n(74, 16), silencio(8), n(62, 16), n(65, 16), n(71, 16),
      n(62, 16), n(65, 16), n(71, 16), silencio(8), n(62, 16), n(65, 16),
      n(71, 16), n(62, 16), n(65, 16), n(71, 16), silencio(8), n(60, 16),
      n(67, 16), n(72, 16), n(60, 16), n(67, 16), n(72, 16), silencio(8),
      n(60, 16), n(67, 16), n(72, 16), n(60, 16), n(67, 16), n(72, 16),
      silencio(8), n(57, 16), n(60, 16), n(65, 16), n(57, 16), n(60, 16),
      n(65, 16), silencio(8), n(57, 16), n(60, 16), n(65, 16), n(57, 16),
      n(60, 16), n(65, 16), silencio(8), n(57, 16), n(60, 16), n(65, 16),
      n(57, 16), n(60, 16), n(65, 16), silencio(8), n(57, 16), n(60, 16),
      n(65, 16), n(57, 16), n(60, 16), n(65, 16), silencio(8), n(55, 16),
      n(59, 16), n(65, 16), n(55, 16), n(59, 16), n(65, 16), silencio(8),
      n(55, 16), n(59, 16), n(65, 16), n(55, 16), n(59, 16), n(65, 16),
      silencio(8), n(55, 16), n(60, 16), n(64, 16), n(55, 16), n(60, 16),
      n(64, 16), silencio(8), n(55, 16), n(60, 16), n(64, 16), n(55, 16),
      n(60, 16), n(64, 16), silencio(8), n(58, 16), n(60, 16), n(64, 16),
      n(58, 16), n(60, 16), n(64, 16), silencio(8), n(58, 16), n(60, 16),
      n(64, 16), n(58, 16), n(60, 16), n(64, 16), silencio(8), n(57, 16),
      n(60, 16), n(64, 16), n(57, 16), n(60, 16), n(64, 16), silencio(8),
      n(57, 16), n(60, 16), n(64, 16), n(57, 16), n(60, 16), n(64, 16),
      silencio(8), n(57, 16), n(60, 16), n(63, 16), n(57, 16), n(60, 16),
      n(63, 16), silencio(8), n(57, 16), n(60, 16), n(63, 16), n(57, 16),
      n(60, 16), n(63, 16), silencio(8), n(59, 16), n(60, 16), n(62, 16),
      n(59, 16), n(60, 16), n(62, 16), silencio(8), n(59, 16), n(60, 16),
      n(62, 16), n(59, 16), n(60, 16), n(62, 16), silencio(8), n(55, 16),
      n(59, 16), n(62, 16), n(55, 16), n(59, 16), n(62, 16), silencio(8),
      n(55, 16), n(59, 16), n(62, 16), n(55, 16), n(59, 16), n(62, 16),
      silencio(8), n(55, 16), n(60, 16), n(64, 16), n(55, 16), n(60, 16),
      n(64, 16), silencio(8), n(55, 16), n(60, 16), n(64, 16), n(55, 16),
      n(60, 16), n(64, 16), silencio(8), n(55, 16), n(59, 16), n(65, 16),
      n(55, 16), n(59, 16), n(65, 16), silencio(8), n(55, 16), n(59, 16),
      n(65, 16), n(55, 16), n(59, 16), n(65, 16), silencio(8), n(57, 16),
      n(60, 16), n(66, 16), n(57, 16), n(60, 16), n(66, 16), silencio(8),
      n(57, 16), n(60, 16), n(66, 16), n(57, 16), n(60, 16), n(66, 16),
      silencio(8), n(55, 16), n(60, 16), n(67, 16), n(55, 16), n(60, 16),
      n(67, 16), silencio(8), n(55, 16), n(60, 16), n(67, 16), n(55, 16),
      n(60, 16), n(67, 16), silencio(8), n(55, 16), n(60, 16), n(65, 16),
      n(55, 16), n(60, 16), n(65, 16), silencio(8), n(55, 16), n(60, 16),
      n(65, 16), n(55, 16), n(60, 16), n(65, 16), silencio(8), n(55, 16),
      n(59, 16), n(65, 16), n(55, 16), n(59, 16), n(65, 16), silencio(8),
      n(55, 16), n(59, 16), n(65, 16), n(55, 16), n(59, 16), n(65, 16),
      silencio(8), n(55, 16), n(58, 16), n(64, 16), n(55, 16), n(58, 16),
      n(64, 16), silencio(8), n(55, 16), n(58, 16), n(64, 16), n(55, 16),
      n(58, 16), n(64, 16), silencio(8), n(53, 16), n(57, 16), n(60, 16),
      n(65, 16), n(60, 16), n(57, 16), n(60, 16), n(57, 16), n(53, 16), n(57, 16),
      n(53, 16), n(50, 16), n(53, 16), n(50, 16), silencio(8), n(67, 16),
      n(71, 16), n(74, 16), n(77, 16), n(74, 16), n(71, 16), n(74, 16), n(71, 16),
      n(67, 16), n(71, 16), n(62, 16), n(65, 16), n(64, 16), n(62, 16),
      n([64, 67, 72], 1),
    ],
    izquierda: [
      [
        silencio(16), n(64, 4, { puntillo: true }), n(64, 16, { ligada: true }),
        silencio(16), n(64, 4, { puntillo: true }), n(64, 16, { ligada: true }),
        silencio(16), n(62, 4, { puntillo: true }), n(62, 16, { ligada: true }),
        silencio(16), n(62, 4, { puntillo: true }), n(62, 16, { ligada: true }),
        silencio(16), n(62, 4, { puntillo: true }), n(62, 16, { ligada: true }),
        silencio(16), n(62, 4, { puntillo: true }), n(62, 16, { ligada: true }),
        silencio(16), n(64, 4, { puntillo: true }), n(64, 16, { ligada: true }),
        silencio(16), n(64, 4, { puntillo: true }), n(64, 16, { ligada: true }),
        silencio(16), n(64, 4, { puntillo: true }), n(64, 16, { ligada: true }),
        silencio(16), n(64, 4, { puntillo: true }), n(64, 16, { ligada: true }),
        silencio(16), n(62, 4, { puntillo: true }), n(62, 16, { ligada: true }),
        silencio(16), n(62, 4, { puntillo: true }), n(62, 16, { ligada: true }),
        silencio(16), n(62, 4, { puntillo: true }), n(62, 16, { ligada: true }),
        silencio(16), n(62, 4, { puntillo: true }), n(62, 16, { ligada: true }),
        silencio(16), n(60, 4, { puntillo: true }), n(60, 16, { ligada: true }),
        silencio(16), n(60, 4, { puntillo: true }), n(60, 16, { ligada: true }),
        silencio(16), n(60, 4, { puntillo: true }), n(60, 16, { ligada: true }),
        silencio(16), n(60, 4, { puntillo: true }), n(60, 16, { ligada: true }),
        silencio(16), n(57, 4, { puntillo: true }), n(57, 16, { ligada: true }),
        silencio(16), n(57, 4, { puntillo: true }), n(57, 16, { ligada: true }),
        silencio(16), n(59, 4, { puntillo: true }), n(59, 16, { ligada: true }),
        silencio(16), n(59, 4, { puntillo: true }), n(59, 16, { ligada: true }),
        silencio(16), n(58, 4, { puntillo: true }), n(58, 16, { ligada: true }),
        silencio(16), n(58, 4, { puntillo: true }), n(58, 16, { ligada: true }),
        silencio(16), n(57, 4, { puntillo: true }), n(57, 16, { ligada: true }),
        silencio(16), n(57, 4, { puntillo: true }), n(57, 16, { ligada: true }),
        silencio(16), n(56, 4, { puntillo: true }), n(56, 16, { ligada: true }),
        silencio(16), n(56, 4, { puntillo: true }), n(56, 16, { ligada: true }),
        silencio(16), n(55, 4, { puntillo: true }), n(55, 16, { ligada: true }),
        silencio(16), n(55, 4, { puntillo: true }), n(55, 16, { ligada: true }),
        silencio(16), n(53, 4, { puntillo: true }), n(53, 16, { ligada: true }),
        silencio(16), n(53, 4, { puntillo: true }), n(53, 16, { ligada: true }),
        silencio(16), n(53, 4, { puntillo: true }), n(53, 16, { ligada: true }),
        silencio(16), n(53, 4, { puntillo: true }), n(53, 16, { ligada: true }),
        silencio(16), n(50, 4, { puntillo: true }), n(50, 16, { ligada: true }),
        silencio(16), n(50, 4, { puntillo: true }), n(50, 16, { ligada: true }),
        silencio(16), n(52, 4, { puntillo: true }), n(52, 16, { ligada: true }),
        silencio(16), n(52, 4, { puntillo: true }), n(52, 16, { ligada: true }),
        silencio(16), n(55, 4, { puntillo: true }), n(55, 16, { ligada: true }),
        silencio(16), n(55, 4, { puntillo: true }), n(55, 16, { ligada: true }),
        silencio(16), n(53, 4, { puntillo: true }), n(53, 16, { ligada: true }),
        silencio(16), n(53, 4, { puntillo: true }), n(53, 16, { ligada: true }),
        silencio(16), n(48, 4, { puntillo: true }), n(48, 16, { ligada: true }),
        silencio(16), n(48, 4, { puntillo: true }), n(48, 16, { ligada: true }),
        silencio(16), n(53, 4, { puntillo: true }), n(53, 16, { ligada: true }),
        silencio(16), n(53, 4, { puntillo: true }), n(53, 16, { ligada: true }),
        silencio(16), n(53, 4, { puntillo: true }), n(53, 16, { ligada: true }),
        silencio(16), n(53, 4, { puntillo: true }), n(53, 16, { ligada: true }),
        silencio(16), n(52, 4, { puntillo: true }), n(52, 16, { ligada: true }),
        silencio(16), n(52, 4, { puntillo: true }), n(52, 16, { ligada: true }),
        silencio(16), n(50, 4, { puntillo: true }), n(50, 16, { ligada: true }),
        silencio(16), n(50, 4, { puntillo: true }), n(50, 16, { ligada: true }),
        silencio(16), n(51, 4, { puntillo: true }), n(51, 16, { ligada: true }),
        silencio(16), n(51, 4, { puntillo: true }), n(51, 16, { ligada: true }),
        silencio(16), n(52, 4, { puntillo: true }), n(52, 16, { ligada: true }),
        silencio(16), n(52, 4, { puntillo: true }), n(52, 16, { ligada: true }),
        silencio(16), n(50, 4, { puntillo: true }), n(50, 16, { ligada: true }),
        silencio(16), n(50, 4, { puntillo: true }), n(50, 16, { ligada: true }),
        silencio(16), n(50, 4, { puntillo: true }), n(50, 16, { ligada: true }),
        silencio(16), n(50, 4, { puntillo: true }), n(50, 16, { ligada: true }),
        silencio(16), n(48, 4, { puntillo: true }), n(48, 16, { ligada: true }),
        silencio(16), n(48, 4, { puntillo: true }), n(48, 16, { ligada: true }),
        silencio(16), n(48, 2, { puntillo: true }),
        n(48, 8, { puntillo: true, ligada: true }), silencio(16),
        n(47, 2, { puntillo: true }), n(47, 8, { puntillo: true, ligada: true }),
        silencio(1),
      ],
      [
        n(60, 2), n(60, 2), n(60, 2), n(60, 2), n(59, 2), n(59, 2), n(60, 2),
        n(60, 2), n(60, 2), n(60, 2), n(60, 2), n(60, 2), n(59, 2), n(59, 2),
        n(59, 2), n(59, 2), n(57, 2), n(57, 2), n(50, 2), n(50, 2), n(55, 2),
        n(55, 2), n(55, 2), n(55, 2), n(53, 2), n(53, 2), n(53, 2), n(53, 2),
        n(52, 2), n(52, 2), n(52, 2), n(52, 2), n(50, 2), n(50, 2), n(43, 2),
        n(43, 2), n(48, 2), n(48, 2), n(48, 2), n(48, 2), n(41, 2), n(41, 2),
        n(42, 2), n(42, 2), n(44, 2), n(44, 2), n(43, 2), n(43, 2), n(43, 2),
        n(43, 2), n(43, 2), n(43, 2), n(43, 2), n(43, 2), n(43, 2), n(43, 2),
        n(43, 2), n(43, 2), n(43, 2), n(43, 2), n(36, 2), n(36, 2), n(36, 1),
        n(36, 1), n([36, 48], 1),
      ],
    ],
  },
  {
    slug: "claro-de-luna",
    fuente: "/fuentes/claro-de-luna.mxl",
    titulo: "Claro de luna",
    compositor: "Beethoven",
    anio: "1801",
    compas: { numerador: 4, denominador: 4 },
    tonalidad: { tonica: 1, modo: "menor" },
    bpm: 54,
    dificultad: 4,
    sobre: 
      "El primer movimiento de la sonata Op. 27 nº 2, entero. La derecha hace dos cosas a la vez y por eso va en dos voces: abajo el arpegio de tresillos que no para nunca, arriba la melodía con su propio ritmo. Fijate cómo las plicas de una van para arriba y las de la otra para abajo — es lo que permite leerlas separadas aunque compartan el pentagrama.",
    revisar:
      "Importada de un MusicXML, con sus tresillos y sus dos voces. La izquierda del original llega a tener cuatro voces en algunos pasajes y sólo entran dos: se quedaron las que más notas tienen, y se perdieron 118 notas de las otras. Es la limitación que queda.",
    hasta: "El movimiento completo, sesenta y nueve compases.",
    derecha: [
      [
        n(56, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(57, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), n(62, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(57, 8, { irregular: TRESILLO }),
        n(62, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), n(60, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(60, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        silencio(2), silencio(4), n(68, 8, { puntillo: true }), n(68, 16),
        n(68, 2, { puntillo: true }), n(68, 8, { puntillo: true }), n(68, 16),
        n(68, 2), n(69, 2), n(68, 2), n(66, 4), n(71, 4), n(64, 4), silencio(4),
        silencio(2), silencio(2), silencio(4), n(67, 8, { puntillo: true }),
        n(67, 16), n(67, 2, { puntillo: true }), n(67, 8, { puntillo: true }),
        n(67, 16), n(67, 2, { puntillo: true }), n(66, 4), n(66, 2), n(67, 4),
        n(64, 4), n(66, 2), n(66, 2), n(59, 4), silencio(4), silencio(4), n(71, 4),
        n(72, 2, { puntillo: true }), n(70, 4), n(71, 2, { puntillo: true }),
        n(71, 4), n(72, 2, { puntillo: true }), n(70, 4), n(71, 2), n(71, 2),
        n(71, 2), n(69, 2), n(67, 2), n(66, 2), n(61, 2), n(61, 4), n(61, 4),
        silencio(4), silencio(4), silencio(4), n(73, 8, { puntillo: true }),
        n(73, 16), n(73, 2, { puntillo: true }), n(73, 8, { puntillo: true }),
        n(73, 16), n(73, 2), n(72, 4), n(73, 4), n(75, 2, { puntillo: true }),
        n(75, 4), n(76, 2), n(75, 4), n(73, 4), n(72, 8, { irregular: TRESILLO }),
        n(60, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(68, 4), n(69, 4), n(66, 4), silencio(8, { irregular: TRESILLO }),
        n(60, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        silencio(1, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(73, 4), n(76, 4), n(73, 4),
        silencio(8, { irregular: TRESILLO }), silencio(1, { irregular: TRESILLO }),
        silencio(4), silencio(4), n(60, 8, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(60, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(72, 8, { irregular: TRESILLO }),
        silencio(4), n(64, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(73, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(76, 8, { irregular: TRESILLO }),
        n(73, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(67, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(70, 8, { irregular: TRESILLO }),
        n(67, 8, { irregular: TRESILLO }), n(73, 8, { irregular: TRESILLO }),
        n(70, 8, { irregular: TRESILLO }), n(76, 8, { irregular: TRESILLO }),
        n(73, 8, { irregular: TRESILLO }), n(79, 8, { irregular: TRESILLO }),
        n(76, 8, { irregular: TRESILLO }), n(82, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(72, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(75, 8, { irregular: TRESILLO }),
        n(72, 8, { irregular: TRESILLO }), n(78, 8, { irregular: TRESILLO }),
        n(75, 8, { irregular: TRESILLO }), n(81, 8, { irregular: TRESILLO }),
        n(78, 8, { irregular: TRESILLO }), n(84, 8, { irregular: TRESILLO }),
        n(81, 8, { irregular: TRESILLO }), n(87, 8, { irregular: TRESILLO }),
        n(84, 8, { irregular: TRESILLO }), n(78, 8, { irregular: TRESILLO }),
        n(81, 8, { irregular: TRESILLO }), n(75, 8, { irregular: TRESILLO }),
        n(78, 8, { irregular: TRESILLO }), n(72, 8, { irregular: TRESILLO }),
        n(75, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(72, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(60, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), silencio(1, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), silencio(1), silencio(1), silencio(1),
        silencio(1), silencio(2), silencio(4), n(68, 8, { puntillo: true }),
        n(68, 16), n(68, 2, { puntillo: true }), n(68, 8, { puntillo: true }),
        n(68, 16), n(68, 2), n(69, 2), n(68, 2), n(66, 4), n(71, 4), n(64, 4),
        silencio(4), silencio(4), n(71, 8, { puntillo: true }), n(71, 16),
        n(71, 2, { puntillo: true }), n(71, 8, { puntillo: true }), n(71, 16),
        n(71, 2), n(72, 4), n(73, 4), n(75, 2), n(76, 2), n(74, 2), n(72, 2),
        n(73, 2, { puntillo: true }), n(73, 4), n(74, 2, { puntillo: true }),
        n(72, 4), n(73, 2, { puntillo: true }), n(73, 4),
        n(74, 2, { puntillo: true }), n(72, 4), n(73, 2), n(73, 2),
        n(71, 2, { puntillo: true }), n(71, 4), n(69, 4), n(69, 4), n(68, 4),
        n(68, 4), n(66, 2), n(68, 4), n(69, 4), n(68, 2), n(68, 2),
        silencio(2, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(73, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(76, 8, { irregular: TRESILLO }), n(73, 8, { irregular: TRESILLO }),
        n(80, 8, { irregular: TRESILLO }), n(76, 8, { irregular: TRESILLO }),
        n(73, 8, { irregular: TRESILLO }), n(72, 8, { irregular: TRESILLO }),
        n(75, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(72, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), silencio(2, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(73, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(76, 8, { irregular: TRESILLO }),
        n(73, 8, { irregular: TRESILLO }), n(80, 8, { irregular: TRESILLO }),
        n(76, 8, { irregular: TRESILLO }), n(73, 8, { irregular: TRESILLO }),
        n(72, 8, { irregular: TRESILLO }), n(75, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(72, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        silencio(2, { irregular: TRESILLO }), silencio(2),
        silencio(8, { irregular: TRESILLO }), silencio(2, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        silencio(2, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        silencio(2), silencio(2), n(61, 2), n(61, 1),
      ],
      [
        silencio(1), silencio(1), silencio(1), silencio(1),
        silencio(2, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(65, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(65, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(65, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(65, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(4), silencio(1), silencio(1),
        n(59, 8, { irregular: TRESILLO }), n(62, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(62, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(67, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(67, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(67, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(67, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(67, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(67, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(67, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(67, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(62, 8, { irregular: TRESILLO }),
        n(65, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(62, 8, { irregular: TRESILLO }), n(65, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(57, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        silencio(1), silencio(1), silencio(2, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(71, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(71, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(71, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(71, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(60, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(73, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(73, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(70, 8, { irregular: TRESILLO }),
        silencio(4), n(68, 8, { irregular: TRESILLO }),
        n(60, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(60, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(60, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        silencio(2, { irregular: TRESILLO }), n(60, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(60, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(60, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), silencio(4),
        n(73, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(76, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(73, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), silencio(1), silencio(1), silencio(1),
        silencio(1), silencio(1), silencio(1), silencio(1), silencio(1),
        silencio(1), silencio(1), silencio(1), silencio(2),
        silencio(8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(60, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(73, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(73, 8, { irregular: TRESILLO }),
        n(62, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(62, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(60, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(60, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(65, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(65, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(65, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(65, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(65, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(65, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(65, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(65, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(57, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        silencio(1), silencio(1), n(61, 4), silencio(1, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), silencio(1), silencio(1), silencio(1),
        silencio(1), silencio(1), silencio(1), silencio(1), silencio(1),
        silencio(1),
      ],
    ],
    izquierda: [
      [
        silencio(1), silencio(1), silencio(1), silencio(1),
        n(52, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        silencio(4, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        silencio(4, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        silencio(4, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        silencio(4, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        silencio(4, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        silencio(4, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        silencio(4, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        silencio(4, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        silencio(4, { irregular: TRESILLO }), n(57, 8, { irregular: TRESILLO }),
        silencio(4, { irregular: TRESILLO }), n(57, 8, { irregular: TRESILLO }),
        silencio(4, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(57, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(55, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(55, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(55, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(55, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(55, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(55, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(55, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(55, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(55, 8, { irregular: TRESILLO }),
        n(60, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(55, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(55, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(54, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(54, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(62, 8, { irregular: TRESILLO }),
        n(54, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(62, 8, { irregular: TRESILLO }), n(55, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(52, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(54, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(62, 8, { irregular: TRESILLO }),
        n(54, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(62, 8, { irregular: TRESILLO }), n(54, 8, { irregular: TRESILLO }),
        n(58, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(54, 8, { irregular: TRESILLO }), n(58, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), silencio(1), silencio(1), silencio(1),
        silencio(1), silencio(1), silencio(1), n(55, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(62, 8, { irregular: TRESILLO }),
        n(55, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(62, 8, { irregular: TRESILLO }), n(54, 8, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(54, 8, { irregular: TRESILLO }), n(57, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(49, 8, { irregular: TRESILLO }),
        n(54, 8, { irregular: TRESILLO }), n(57, 8, { irregular: TRESILLO }),
        n(49, 8, { irregular: TRESILLO }), n(54, 8, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), n(49, 8, { irregular: TRESILLO }),
        n(54, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(49, 8, { irregular: TRESILLO }), n(53, 8, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), n(54, 8, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        silencio(2), silencio(8, { irregular: TRESILLO }), silencio(1), silencio(1),
        silencio(1), silencio(1), silencio(1), silencio(4),
        n(56, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(54, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        silencio(1), silencio(4), n(61, 8, { irregular: TRESILLO }),
        n(52, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(52, 8, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(52, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        silencio(1), silencio(1), silencio(1), silencio(1), silencio(1),
        silencio(2), n(57, 8, { irregular: TRESILLO }),
        n(51, 4, { irregular: TRESILLO }),
        n(49, 4, { puntillo: true, irregular: TRESILLO }), n(48, 2), n(51, 4),
        n(49, 4), n(48, 2), n(50, 4), n(49, 4), n(48, 2), silencio(2), silencio(1),
        n(52, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), silencio(1, { irregular: TRESILLO }),
        silencio(4), silencio(1), silencio(1), silencio(1), silencio(1),
        silencio(1), silencio(1), silencio(1), silencio(1), silencio(1),
        silencio(1), silencio(1), n(54, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(54, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(54, 8, { irregular: TRESILLO }),
        n(60, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(54, 8, { irregular: TRESILLO }), n(60, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), silencio(1), silencio(1), silencio(1),
        silencio(1, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(60, 4), silencio(1), silencio(1, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(60, 4), silencio(1), silencio(1),
        silencio(2), n([52, 56], 2), n([52, 56], 1),
      ],
      [
        n([37, 49], 1), n([35, 47], 1), n([33, 45], 2), n([30, 42], 2),
        n([32, 44], 2), n([32, 44], 2), n([37, 44, 49], 1), n([36, 44, 48], 1),
        n([37, 49], 2), n([30, 42], 2), n([35, 47], 2), n([35, 47], 2),
        n([40, 52], 1), n([40, 52], 1), n([38, 50], 1), n([36, 48], 4),
        n([35, 47], 4), n([34, 46], 2), n([35, 47], 2), n(40, 4), n(43, 4),
        n(42, 2), n([30, 42], 2), n([35, 47], 1), n([35, 47], 4, { ligada: true }),
        n([40, 52], 4), n([43, 55], 4), n([40, 52], 4), n([35, 47], 1),
        n([35, 47], 4, { ligada: true }), n([40, 52], 4), n([43, 55], 4),
        n([40, 52], 4), n([35, 47], 2), n([32, 44], 2), n([29, 41], 2),
        n([30, 42], 2), n([35, 47], 2), n([36, 48], 2), n(37, 2), n(37, 2),
        n([30, 37, 42], 1), n([41, 49, 53], 1), n([42, 54], 2), n([39, 51], 4),
        n([37, 49], 4), n([36, 44, 48], 2, { puntillo: true }), n([36, 44, 48], 4),
        n([37, 44, 49], 2), n([30, 42], 4), n([31, 43], 4), n([32, 44], 1),
        n([32, 44], 1), n([32, 44], 1), n([32, 44], 1), n([32, 44], 1),
        n([32, 44], 1), n([32, 44], 1), n([32, 44], 1),
        n([32, 44], 1, { ligada: true }), n([32, 44], 1, { ligada: true }),
        n([32, 44], 1), n([32, 44], 1), n([32, 44], 2), n([33, 45], 2),
        n([30, 42], 2), n([32, 44], 2), n([37, 44, 49], 1), n([36, 44, 48], 1),
        n([37, 49], 2), n([30, 42], 2), n([35, 47], 2), n([35, 47], 2),
        n([40, 52], 1), n([39, 51], 1), n([40, 52], 2), n([39, 51], 4),
        n([37, 49], 4), n([36, 44, 48], 2), n([37, 44, 49], 2), n([30, 42], 2),
        n([32, 44], 2), n([37, 49], 1), n([37, 49], 4, { ligada: true }),
        n([42, 54], 4), n([45, 57], 4), n([42, 54], 4), n([37, 49], 1),
        n([37, 49], 4, { ligada: true }), n([42, 54], 4), n([45, 57], 4),
        n([42, 54], 4), n([37, 49], 2), n([30, 42], 2),
        n([39, 51], 2, { puntillo: true }), n([40, 52], 4), n([37, 49], 4),
        n([39, 51], 4), n([36, 48], 4), n([37, 49], 4), n([33, 45], 2),
        n([32, 44], 4), n([30, 42], 4), n([32, 44], 2), n([32, 44], 2),
        n(44, 2, { puntillo: true }), n(44, 8, { puntillo: true }), n(44, 16),
        n(44, 2, { puntillo: true }), n(44, 8, { puntillo: true }), n(44, 16),
        n(44, 2, { puntillo: true }), n(44, 8, { puntillo: true }), n(44, 16),
        n(44, 2, { puntillo: true }), n(44, 8, { puntillo: true }), n(44, 16),
        n(44, 2, { puntillo: true }), n(44, 8, { puntillo: true }), n(44, 16),
        n(44, 2, { puntillo: true }), n(44, 8, { puntillo: true }), n(44, 16),
        n(44, 2), n(49, 2), n(44, 2), n(44, 8, { irregular: TRESILLO }),
        n(49, 8, { irregular: TRESILLO }), n(44, 8, { irregular: TRESILLO }),
        n(40, 8, { irregular: TRESILLO }), n(44, 8, { irregular: TRESILLO }),
        n(40, 8, { irregular: TRESILLO }), n(37, 2), n([37, 44, 49], 2),
        n([37, 44, 49], 1),
      ],
    ],
  },

  {
    slug: "canon-en-re",
    fuente: "/fuentes/canon-en-re.mxl",
    titulo: "Canon en Re",
    compositor: "Pachelbel",
    anio: "c. 1690",
    compas: { numerador: 4, denominador: 4 },
    tonalidad: { tonica: 2, modo: "mayor" },
    bpm: 50,
    dificultad: 2,
    sobre: 
      "La izquierda es el bajo más famoso de la historia: ocho notas que dan vueltas y sobre las que se escribieron miles de canciones. Se puede estudiar sola —son las mismas ocho cada dos compases— y la derecha entra recién en el quinto.",
    revisar:
      "Importada de un MusicXML, así que las alturas y las figuras salen del archivo y no de nuestra memoria.",
    hasta: "Los primeros ocho compases de un arreglo fácil.",
    derecha: [
      silencio(1), silencio(1), silencio(1), silencio(1), n(78, 2), n(76, 2),
      n(74, 2), n(73, 2), n(71, 2), n(69, 2), n(71, 2), n(73, 2),
    ],
    izquierda: [
      n(50, 8), n(54, 8), n(57, 8), n(62, 8), n(45, 8), n(49, 8), n(52, 8),
      n(57, 8), n(47, 8), n(50, 8), n(54, 8), n(59, 8), n(42, 8), n(45, 8),
      n(49, 8), n(54, 8), n(43, 8), n(47, 8), n(50, 8), n(55, 8), n(38, 8),
      n(42, 8), n(45, 8), n(50, 8), n(43, 8), n(47, 8), n(50, 8), n(55, 8),
      n(45, 8), n(49, 8), n(52, 8), n(57, 8), n(50, 8), n(54, 8), n(57, 8),
      n(62, 8), n(45, 8), n(49, 8), n(52, 8), n(57, 8), n(47, 8), n(50, 8),
      n(54, 8), n(59, 8), n(42, 8), n(45, 8), n(49, 8), n(54, 8), n(43, 8),
      n(47, 8), n(50, 8), n(55, 8), n(38, 8), n(42, 8), n(45, 8), n(50, 8),
      n(43, 8), n(47, 8), n(50, 8), n(55, 8), n(45, 8), n(49, 8), n(52, 8),
      n(57, 8),
    ],
  },

  {
    slug: "minueto-en-sol",
    fuente: "/fuentes/minueto-en-sol.mxl",
    titulo: "Minueto en Sol",
    compositor: "Christian Petzold",
    anio: "c. 1725",
    compas: { numerador: 3, denominador: 4 },
    tonalidad: { tonica: 7, modo: "mayor" },
    bpm: 80,
    dificultad: 2,
    sobre: 
      "El primer minueto que estudia todo el mundo. Estuvo doscientos años atribuido a Bach porque apareció en un cuaderno suyo, y resultó ser de Petzold. Una mano por vez y sale: la derecha es melodía pura y la izquierda casi no se mueve.",
    revisar:
      "Importada de un MusicXML.",
    hasta: "Los primeros dieciséis compases, o sea la primera parte.",
    derecha: [
      n(74, 4), n(67, 8), n(69, 8), n(71, 8), n(72, 8), n(74, 4), n(67, 4),
      n(67, 4), n(76, 4), n(72, 8), n(74, 8), n(76, 8), n(78, 8), n(79, 4),
      n(67, 4), n(67, 4), n(72, 4), n(74, 8), n(72, 8), n(71, 8), n(69, 8),
      n(71, 4), n(72, 8), n(71, 8), n(69, 8), n(67, 8), n(66, 4), n(67, 8),
      n(69, 8), n(71, 8), n(67, 8), n(71, 4), n(69, 2), n(74, 4), n(67, 8),
      n(69, 8), n(71, 8), n(72, 8), n(74, 4), n(67, 4), n(67, 4), n(76, 4),
      n(72, 8), n(74, 8), n(76, 8), n(78, 8), n(79, 4), n(67, 4), n(67, 4),
      n(72, 4), n(74, 8), n(72, 8), n(71, 8), n(69, 8), n(71, 4), n(72, 8),
      n(71, 8), n(69, 8), n(67, 8), n(69, 4), n(71, 8), n(69, 8), n(67, 8),
      n(66, 8), n(67, 2, { puntillo: true }),
    ],
    izquierda: [
      n([55, 59, 62], 2), n(57, 4), n(59, 2, { puntillo: true }),
      n(60, 2, { puntillo: true }), n(59, 2, { puntillo: true }),
      n(57, 2, { puntillo: true }), n(55, 2, { puntillo: true }), n(62, 4),
      n(59, 4), n(55, 4), n(62, 4), n(50, 8), n(60, 8), n(59, 8), n(57, 8),
      n(59, 2), n(57, 4), n(55, 4), n(59, 4), n(55, 4),
      n(60, 2, { puntillo: true }), n(59, 4), n(60, 8), n(59, 8), n(57, 8),
      n(55, 8), n(57, 2), n(54, 4), n(55, 2), n(59, 4), n(60, 4), n(62, 4),
      n(50, 4), n(55, 2), n(43, 4),
    ],
  },

  {
    slug: "para-elisa",
    fuente: "/fuentes/para-elisa.mxl",
    titulo: "Para Elisa",
    compositor: "Beethoven",
    anio: "1810",
    compas: { numerador: 3, denominador: 8 },
    tonalidad: { tonica: 9, modo: "menor" },
    bpm: 120,
    dificultad: 3,
    sobre: 
      "El arranque que todo el mundo tiene en la cabeza. Fijate el compás: 3/8, tres corcheas por compás, así que el pulso va bastante más rápido de lo que el número sugiere.",
    revisar:
      "Importada de un MusicXML. Arranca con anacrusa —dos semicorcheas antes del primer compás— y nuestro modelo no tiene compases incompletos, así que se rellenó con silencios: los números de compás quedan corridos uno respecto de la edición.",
    hasta: "Los primeros dieciséis compases.",
    derecha: [
      silencio(4), n(76, 16), n(75, 16), n(76, 16), n(75, 16), n(76, 16),
      n(71, 16), n(74, 16), n(72, 16), n(69, 8), silencio(16), n(60, 16),
      n(64, 16), n(69, 16), n(71, 8), silencio(16), n(64, 16), n(68, 16),
      n(71, 16), n(72, 8), silencio(16), n(64, 16), n(76, 16), n(75, 16),
      n(76, 16), n(75, 16), n(76, 16), n(71, 16), n(74, 16), n(72, 16), n(69, 8),
      silencio(16), n(60, 16), n(64, 16), n(69, 16), n(71, 8), silencio(16),
      n(64, 16), n(72, 16), n(71, 16), n(69, 4), silencio(8), n(69, 8),
      silencio(16), n(71, 16), n(72, 16), n(74, 16), n(76, 8, { puntillo: true }),
      n(67, 16), n(77, 16), n(76, 16), n(74, 8, { puntillo: true }), n(65, 16),
      n(76, 16), n(74, 16), n(72, 8, { puntillo: true }), n(64, 16), n(74, 16),
      n(72, 16), n(71, 8), silencio(16), n(64, 16), n(76, 16), silencio(16),
      silencio(16), n(76, 16), n(88, 16), silencio(16), silencio(16), n(75, 16),
      n(76, 16), silencio(16), silencio(16), n(75, 16), n(76, 16), n(75, 16),
      n(76, 16), n(75, 16), n(76, 16), n(71, 16), n(74, 16), n(72, 16),
    ],
    izquierda: [
      silencio(4), silencio(8), silencio(4, { puntillo: true }), n(45, 16),
      n(52, 16), n(57, 16), silencio(16), silencio(8), n(40, 16), n(52, 16),
      n(56, 16), silencio(16), silencio(8), n(45, 16), n(52, 16), n(57, 16),
      silencio(16), silencio(8), silencio(4, { puntillo: true }), n(45, 16),
      n(52, 16), n(57, 16), silencio(16), silencio(8), n(40, 16), n(52, 16),
      n(56, 16), silencio(16), silencio(8), n(45, 16), n(52, 16), n(57, 16),
      silencio(16), silencio(8), n(45, 16), n(52, 16), n(57, 16), silencio(16),
      silencio(8), n(48, 16), n(55, 16), n(60, 16), silencio(16), silencio(8),
      n(43, 16), n(55, 16), n(59, 16), silencio(16), silencio(8), n(45, 16),
      n(52, 16), n(57, 16), silencio(16), silencio(8), n(40, 16), n(52, 16),
      n(64, 16), silencio(16), silencio(16), n(64, 16), n(76, 16), silencio(16),
      silencio(16), n(75, 16), n(76, 16), silencio(16), silencio(16), n(75, 16),
      n(76, 16), silencio(16), silencio(8), silencio(4, { puntillo: true }),
    ],
  },

  {
    slug: "la-vuelta-en-do",
    titulo: "La vuelta en Do",
    compositor: "Joaquín",
    anio: "2026",
    // 12/8 porque es lo que se tocó: doce corcheas parejas por compás, el
    // pulso de a tres — el compuesto de la clase, sin un solo tresillo.
    compas: { numerador: 12, denominador: 8 },
    tonalidad: { tonica: 0, modo: "mayor" },
    bpm: 104,
    dificultad: 2,
    propia: true,
    sobre:
      "La primera pieza propia del cuaderno, improvisada y grabada el mismo día en que la vuelta empezó a salir, con sus dos secciones. Es la progresión de los doo-wop de los cincuenta —I · VIm · IV · V— con la izquierda arpegiando en corcheas. En la vuelta quieta la melodía es una sola nota: el mismo Do es la fundamental del Do, la tercera del Lam y la quinta del Fa, tres acordes recibiendo a la misma guía. En la vuelta que sube las guías trepan —Do, Mi, Fa, Sol, una por acorde— y las corcheas de contratiempo del final de cada compás las conectan por grado conjunto. Las dos cierran igual: la bajada Sol–Fa–Mi–Re, y el Do de la llegada cayendo justo con la vuelta a la casa.",
    hasta: "Entera: la vuelta quieta, la vuelta que sube y el cierre.",
    revisar:
      "Transcripta de las grabaciones MIDI de la página de grabar (30 de agosto), cuantizada a la corchea pareja. La primera toma repetía la vuelta quieta cuatro veces, con la melodía una octava arriba y el pulso apurándose de ~104 a ~124; la forma final —quieta, sube, cierre— es la de la tercera toma, y quedó ésa.",
    derecha: [
      // La vuelta quieta: el Do tenido casi el compás entero, y el
      // contratiempo en la última corchea anticipando lo que viene.
      n(Do4, 2, { puntillo: true }), n(Do4, 4, { puntillo: true, ligada: true }), n(Do4, 4, { ligada: true }), n(Re4, 8),
      n(Do4, 2, { puntillo: true }), n(Do4, 4, { puntillo: true, ligada: true }), n(Do4, 4, { ligada: true }), n(Mi4, 8),
      n(Do4, 2, { puntillo: true }), n(Do4, 4, { puntillo: true, ligada: true }), n(Do4, 4, { ligada: true }), n(Fa4, 8),
      // Sol: la bajada Sol–Fa–Mi–Re tejida entre los pulsos.
      n(Re4, 4, { puntillo: true }), n(Re4, 4, { ligada: true }), n(Sol4, 8), n(Fa4, 4), n(Mi4, 8), n(Re4, 4), n(Mi4, 8),
      // La vuelta que sube: las guías trepando Do → Mi → Fa → Sol, y la
      // misma bajada cerrando el arco.
      n(Do4, 2, { puntillo: true }), n(Do4, 4, { puntillo: true, ligada: true }), n(Do4, 4, { ligada: true }), n(Re4, 8),
      n(Mi4, 2, { puntillo: true }), n(Mi4, 4, { puntillo: true, ligada: true }), n(Mi4, 4, { ligada: true }), n(Re4, 8),
      n(Fa4, 2, { puntillo: true }), n(Fa4, 4, { puntillo: true, ligada: true }), n(Fa4, 4, { ligada: true }), n(Mi4, 8),
      n(Sol4, 4, { puntillo: true }), n(Sol4, 4, { ligada: true }), n(Sol4, 8), n(Fa4, 4), n(Mi4, 8), n(Re4, 4), n(Mi4, 8),
      // El cierre: el Do del arpegio rodado queda arriba, en la mano que canta.
      n(Do4, 2, { puntillo: true }), n(Do4, 2, { puntillo: true }),
    ],
    izquierda: [
      ...repetir(
        [
          // Cada acorde arpegiado igual: fundamental, tercera, quinta,
          // octava y de vuelta — la misma mano trasladada de acorde en acorde.
          ...repetir([n(Do3, 8), n(Mi3, 8), n(Sol3, 8), n(Do4, 8), n(Sol3, 8), n(Mi3, 8)], 2),
          ...repetir([n(La2, 8), n(Do3, 8), n(Mi3, 8), n(La3, 8), n(Mi3, 8), n(Do3, 8)], 2),
          ...repetir([n(Fa2, 8), n(La2, 8), n(Do3, 8), n(Fa3, 8), n(Do3, 8), n(La2, 8)], 2),
          ...repetir([n(Sol2, 8), n(Si2, 8), n(Re3, 8), n(Sol3, 8), n(Re3, 8), n(Si2, 8)], 2),
        ],
        2,
      ),
      // Media vuelta más de arpegio y el acorde plantado — su Do de arriba
      // está escrito en la derecha, que es adonde llega el rodado.
      n(Do3, 8), n(Mi3, 8), n(Sol3, 8), n(Do4, 8), n(Sol3, 8), n(Mi3, 8),
      n([Do3, Mi3, Sol3], 2, { puntillo: true }),
    ],
  },

  {
    slug: "cuesta-abajo-en-inversion",
    titulo: "Cuesta abajo en inversión",
    compositor: "Joaquín",
    anio: "2026",
    // 2/4 porque la célula de cuatro corcheas ES el compás: la armonía cambia
    // de célula en célula, y las frases de tres y de cuatro compases quedan
    // como se tocaron en vez de partir un 4/4 por la mitad.
    compas: { numerador: 2, denominador: 4 },
    tonalidad: { tonica: 0, modo: "mayor" },
    bpm: 104,
    dificultad: 2,
    propia: true,
    sobre:
      "La segunda pieza propia, y la primera que se anima a los acordes con barra: el bajo baja —Do, Si, La— y quien lo sostiene son las inversiones del renglón de la clase 4. Las dos vueltas comparten ese camino y se separan en el fondo: la primera descansa en Lam y la segunda pone Dm/A sobre el mismo La del bajo —mismo bajo, otra función— y guarda el Fa, su nota más tensa, para el Si disminuido que pide la vuelta a casa. Arriba el Mi vuelve a contratiempo mientras las guías cambian con cada acorde. El título es el chiste y es la verdad: acá lo que baja es el bajo.",
    hasta: "Entera: las dos vueltas con su giro distinto y el cierre.",
    revisar:
      "Transcripta de la grabación MIDI de la página de grabar (30 de agosto), cuantizada a la corchea. Las frases no miden todas lo mismo —el Lam dura tres compases y el Dm/A cuatro— y así se tocó: no es un error de cuenta. Alguna nota fantasma de la toma, apretada casi sin sonar, quedó afuera.",
    derecha: [
      // La anacrusa: el Mi entra una corchea antes que todo.
      silencio(4, { puntillo: true }), n(Mi4, 8),
      // Vuelta 1 · Do: el suspiro Re–Do, con el Mi de contratiempo.
      n(Re4, 4, { puntillo: true }), n(Do4, 8),
      n(Do4, 4, { puntillo: true, ligada: true }), n(Mi4, 8),
      n(Re4, 4, { puntillo: true }), n(Do4, 8),
      n(Do4, 4, { puntillo: true, ligada: true }), n(Mi4, 8),
      // Em/B: la guía baja al Si; el Mi insiste.
      n(Si3, 4, { puntillo: true }), n(Mi4, 8),
      n(Mi4, 4, { puntillo: true, ligada: true }), n(Mi4, 8),
      n(Si3, 4, { puntillo: true }), n(Mi4, 8),
      n(Mi4, 4, { puntillo: true, ligada: true }), n(Mi4, 8),
      // Lam: la vuelta 1 descansa en el Do largo.
      n(Do4, 2),
      n(Do4, 2, { ligada: true }),
      n(Do4, 4, { puntillo: true, ligada: true }), n(Do4, 8),
      // Si°: el Re tenido pide la casa; el Mi de paso la anuncia.
      n(Re4, 2),
      n(Re4, 2, { ligada: true }),
      n(Re4, 4, { puntillo: true, ligada: true }), n(Mi4, 8),
      // Vuelta 2 · Do: el mismo suspiro, dado vuelta — primero el Do.
      n(Do4, 2),
      n(Do4, 4, { puntillo: true, ligada: true }), n(Mi4, 8),
      n(Re4, 4, { puntillo: true }), n(Do4, 8),
      n(Do4, 4, { puntillo: true, ligada: true }), n(Mi4, 8),
      // Em/B, como en la vuelta 1.
      n(Si3, 4, { puntillo: true }), n(Mi4, 8),
      n(Mi4, 4, { puntillo: true, ligada: true }), n(Mi4, 8),
      n(Si3, 4, { puntillo: true }), n(Mi4, 8),
      n(Mi4, 4, { puntillo: true, ligada: true }), n(Do4, 8),
      // Dm/A — el giro: mismo La en el bajo, otro acorde, y la guía es Re.
      n(Re4, 2),
      n(Re4, 2, { ligada: true }),
      n(Re4, 2, { ligada: true }),
      n(Re4, 4, { puntillo: true, ligada: true }), n(Mi4, 8),
      // Si°: el Fa — la nota del tritono, la más tensa de toda la pieza —
      // guardado para acá, y resuelto por grado: Fa, Mi, Do.
      n(Fa4, 2),
      n(Fa4, 2, { ligada: true }),
      n(Fa4, 4, { puntillo: true, ligada: true }), n(Mi4, 8),
      // El cierre: el Do llega, respira dos compases y el rodado lo confirma.
      n(Do4, 2),
      n(Do4, 2, { ligada: true }),
      n(Do4, 2),
    ],
    izquierda: [
      // La anacrusa es de la melodía: la izquierda espera su compás.
      silencio(2),
      // Cada acorde es una célula de cuatro corcheas —fundamental, tercera,
      // quinta, tercera— y la armonía cambia de célula en célula.
      ...repetir([n(Do3, 8), n(Mi3, 8), n(Sol3, 8), n(Mi3, 8)], 4),
      ...repetir([n(Si2, 8), n(Mi3, 8), n(Sol3, 8), n(Mi3, 8)], 4),
      ...repetir([n(La2, 8), n(Do3, 8), n(Mi3, 8), n(Do3, 8)], 3),
      ...repetir([n(Si2, 8), n(Re3, 8), n(Fa3, 8), n(Re3, 8)], 3),
      ...repetir([n(Do3, 8), n(Mi3, 8), n(Sol3, 8), n(Mi3, 8)], 4),
      ...repetir([n(Si2, 8), n(Mi3, 8), n(Sol3, 8), n(Mi3, 8)], 4),
      ...repetir([n(La2, 8), n(Re3, 8), n(Fa3, 8), n(Re3, 8)], 4),
      ...repetir([n(Si2, 8), n(Re3, 8), n(Fa3, 8), n(Re3, 8)], 3),
      ...repetir([n(Do3, 8), n(Mi3, 8), n(Sol3, 8), n(Mi3, 8)], 2),
      // El rodado final, corto: sube y se queda.
      n(Do3, 8), n(Mi3, 8), n(Sol3, 4),
    ],
  },
  {
    slug: "las-tres-llegadas",
    titulo: "Las tres llegadas",
    compositor: "Joaquín",
    anio: "2026",
    // Un vals: bajo en el uno y el acorde en el dos y el tres, que es como se
    // tocó de punta a punta.
    compas: { numerador: 3, denominador: 4 },
    tonalidad: { tonica: 9, modo: "menor" },
    bpm: 84,
    dificultad: 2,
    propia: true,
    sobre:
      "La tercera pieza propia, improvisada la semana de los acordes de paso, y es la tarea de la clase 5 hecha música: un vals en La menor donde tres llegadas vienen preparadas por su dominante secundario de la tabla — B7 → Em, D7 → G, E7 → Am. Cada dominante es un evento y no un acorde de paso de medio compás: la izquierda deja el vals, las dos manos arpegian el acorde para arriba y la melodía baja por grado conjunto hasta la fundamental de adonde llega. Re♯ Fa♯ La, Sol Fa♯, Mi. El gesto ya estaba en el tercer compás —La Do Mi, Sol Fa Mi— y después se repite tres veces sobre los dominantes: un motivo y tres transposiciones. En el B7 la derecha sola toca Re♯ Fa♯ La, que es el Re♯dim de paso de la misma clase: las dos opciones coinciden ahí.",
    hasta: "Entera, con el final provisorio: los cuatro compases de Sol y la rota a Lam quedaron como se tocaron.",
    revisar:
      "Transcripta de la grabación MIDI de la página de grabar (4 de septiembre), cuantizada a la negra. El pulso de la toma se apuraba de ~75 a ~120: acá va parejo a 84. Las notas fantasma (velocity 1 a 9) y un Re3 rozado bajo la llegada a Em quedaron afuera. El Fa♯ del compás 22 estaba tocado solo, con tres segundos de silencio antes del Sol: se le puso un Re con Fa♯ y La abajo, que es el D7 → G que la pieza ya usa, y es una decisión para revisar. El final no está decidido todavía.",
    derecha: [
      // La intro: dos compases de vals solo, y el motivo — arpegio arriba,
      // bajada por grado conjunto — sobre Lam.
      silencio(2, { puntillo: true }),
      n(Mi4, 2, { puntillo: true }),
      n(La3, 4), n(Do4, 4), n(Mi4, 4),
      n(Sol4, 4), n(Fa4, 4), n(Mi4, 4),
      // Si°: el Re tenido, con el Mi vecino de paso.
      n(Re4, 2), n(Mi4, 4),
      n(Re4, 2, { puntillo: true }),
      n(Do4, 2, { puntillo: true }),
      n(Do4, 2, { puntillo: true, ligada: true }),
      // B7 → Em: el motivo sobre el dominante. Si Re♯ Fa♯ arriba, La Sol Fa♯
      // abajo, y el Mi de la llegada.
      n(Si3, 4), n(Res4, 4), n(Fas4, 4),
      n(La4, 4), n(Sol4, 4), n(Fas4, 4),
      n(Mi4, 2, { puntillo: true }),
      n(Mi4, 2, { puntillo: true, ligada: true }),
      // D7 → G: lo mismo, una nota más alto, y las dos manos en octavas.
      n(Re4, 4), n(Fas4, 4), n(La4, 4),
      n(Do5, 4), n(Si4, 4), n(La4, 4),
      n(Sol4, 2, { puntillo: true }),
      n(Sol4, 2, { puntillo: true, ligada: true }),
      // E7 → Am: el principal, y el más alto de los tres: llega al Re5.
      n(Mi4, 4), n(Sols4, 4), n(Si4, 4),
      n(Re5, 4), n(Do5, 4), n(Si4, 4),
      n(La4, 2, { puntillo: true }),
      // La bajada larga, Re Do Si La Sol Fa♯, que va a buscar el Sol.
      n(La4, 2, { ligada: true }), n(Re5, 4),
      n(Do5, 4), n(Si4, 4), n(La4, 4),
      n(Sol4, 4), n(Fas4, 2),
      // Sol: la melodía se queda en el Sol y la izquierda sigue sola.
      n(Sol4, 2, { puntillo: true }),
      n(Sol4, 2, { puntillo: true, ligada: true }),
      silencio(2, { puntillo: true }),
      silencio(2, { puntillo: true }),
      // El acorde de Sol plantado y la rota a Lam: el final que falta.
      silencio(2, { puntillo: true }),
      silencio(2, { puntillo: true }),
    ],
    izquierda: [
      // El vals: bajo, acorde, acorde.
      ...repetir([n(La2, 4), n([Do3, Mi3], 4), n([Do3, Mi3], 4)], 4),
      ...repetir([n(Si2, 4), n([Re3, Fa3], 4), n([Re3, Fa3], 4)], 2),
      ...repetir([n(La2, 4), n([Do3, Mi3], 4), n([Do3, Mi3], 4)], 2),
      // B7: el bajo en Si y arriba Re♯ Fa♯ La — el Re♯dim de paso de la
      // clase, con la fundamental del dominante abajo.
      ...repetir([n(Si2, 4), n([Res3, Fas3, La3], 4), n([Res3, Fas3, La3], 4)], 2),
      ...repetir([n(Mi3, 4), n([Sol3, Si3], 4), n([Sol3, Si3], 4)], 2),
      // D7: la izquierda dobla el motivo en octavas, como se tocó.
      n(Re3, 4), n(Fas3, 4), n(La3, 4),
      n(Do4, 4), n(La3, 4), n(Fas3, 4),
      ...repetir([n(Sol3, 4), n([Si3, Re4], 4), n([Si3, Re4], 4)], 2),
      // E7, en vals otra vez.
      ...repetir([n(Mi3, 4), n([Sols3, Si3, Re4], 4), n([Sols3, Si3, Re4], 4)], 2),
      // Lam una octava arriba de la intro, como en la toma.
      ...repetir([n(La3, 4), n([Do4, Mi4], 4), n([Do4, Mi4], 4)], 3),
      // El Re bajo el Fa♯ (ver revisar): D7 → G.
      n(Re3, 4), n([Fas3, La3], 4), n([Fas3, La3], 4),
      ...repetir([n(Sol2, 4), n([Si2, Re3], 4), n([Si2, Re3], 4)], 4),
      n([Sol2, Si2, Re3], 2, { puntillo: true }),
      n([La2, Do3, Mi3], 2, { puntillo: true }),
    ],
  },
];

/** Repite un grupo de eventos, que es como está escrita la música de verdad. */
function repetir(grupo: Evento[], veces: number): Evento[] {
  return Array.from({ length: veces }, () => grupo.map((e) => ({ ...e }))).flat();
}

export function piezaPorSlug(slug: string): Pieza | undefined {
  return PIEZAS.find((p) => p.slug === slug);
}

