import type { Compas } from "@/lib/ritmo";
import type { Evento, Tonalidad, Voces } from "@/lib/pentagrama";

/**
 * Las partituras, escritas como datos.
 *
 * Igual que las clases: no hay PDF, no hay imagen y no se baja nada. La pieza
 * es una lista de notas con su figura, y el pentagrama se dibuja de eso — así
 * que la app *sabe* qué está sonando y puede tocarlo, seguirte por MIDI y
 * marcarte dónde vas. Con un PDF nada de eso se puede.
 *
 * **Están transcriptas de memoria y son un pedazo.** Las obras son de dominio
 * público (Bach y Beethoven hace bastante que no cobran), pero la transcripción
 * es nuestra y puede tener errores: sale bien el arranque de las conocidas y se
 * pone dudosa en las voces internas. Por eso cada pieza dice hasta qué compás
 * llega y `revisar` marca lo que hay que chequear con el profe. Es la misma
 * regla que `openQuestions` en las clases: mejor la duda anotada que el invento
 * en silencio.
 */

export interface Pieza {
  slug: string;
  titulo: string;
  compositor: string;
  anio: string;
  compas: Compas;
  tonalidad: Tonalidad;
  /** Negras por minuto para el reproductor. */
  bpm: number;
  /**
   * Qué va en cada pentagrama. Una fila de eventos si la mano tiene una sola
   * voz —que es casi siempre— o una lista de filas si tiene dos.
   */
  derecha: Voces;
  izquierda: Voces;
  /** De 1 a 5, para ordenar la lista por lo que se puede intentar hoy. */
  dificultad: number;
  /** Por qué está acá y qué mirar. */
  sobre: string;
  /** Hasta dónde llega lo transcripto. */
  hasta: string;
  /** Lo que habría que chequear. Se muestra al pie, sin culpa. */
  revisar?: string;
  /**
   * El MusicXML del que se importó, si existe, servido desde `public/`. Con él
   * la página ofrece la edición completa (OSMD): todo lo que nuestro modelo
   * todavía no representa — ligaduras, matices, digitación, las voces que el
   * importador deja afuera.
   */
  fuente?: string;
}

/** Atajos para que las piezas se lean como música y no como JSON. */
const n = (midis: number | number[], divide: number, extra: Partial<Evento> = {}): Evento => ({
  midis: Array.isArray(midis) ? midis : [midis],
  divide,
  ...extra,
});
/** Tres en el tiempo de dos, que es el grupo irregular que aparece siempre. */
const TRESILLO = { en: 3, de: 2 } as const;
const silencio = (divide: number, extra: Partial<Evento> = {}): Evento => ({
  midis: [],
  divide,
  ...extra,
});

// Las teclas por nombre, para poder escribir la música leyéndola en vez de
// contar números MIDI. Do central = Do4 = 60.
const Sol2 = 43, Si2 = 47;
const Do3 = 48, Re3 = 50, Mi3 = 52, Sol3 = 55, La3 = 57, Si3 = 59;
const Re2 = 38;
const Do4 = 60, Re4 = 62, Mi4 = 64, Fa4 = 65, Sol4 = 67, La4 = 69, Si4 = 71;
const Do5 = 72, Re5 = 74, Mi5 = 76, Fa5 = 77;

// Las del Claro de luna, en Do♯ menor.
const Fas1 = 30, La1 = 33, Dos2 = 37, Fas2 = 42, La2 = 45, Dos3 = 49;
const Fas3 = 54, Sols3 = 56, Dos4b = 61;

export const PIEZAS: Pieza[] = [
  {
    slug: "oda-a-la-alegria",
    titulo: "Oda a la alegría",
    compositor: "Beethoven",
    anio: "1824",
    compas: { numerador: 4, denominador: 4 },
    tonalidad: { tonica: 0, modo: "mayor" },
    bpm: 100,
    dificultad: 1,
    sobre:
      "Ocho compases, todo por grados conjuntos y sin una sola tecla negra. Es la que se puede tocar hoy: la derecha no se mueve de la posición de cinco dedos y la izquierda son dos acordes que ya sabés armar.",
    hasta: "El tema completo, ocho compases.",
    derecha: [
      // Mi mi fa sol | sol fa mi re | do do re mi | mi. re re
      n(Mi4, 4), n(Mi4, 4), n(Fa4, 4), n(Sol4, 4),
      n(Sol4, 4), n(Fa4, 4), n(Mi4, 4), n(Re4, 4),
      n(Do4, 4), n(Do4, 4), n(Re4, 4), n(Mi4, 4),
      n(Mi4, 4, { puntillo: true }), n(Re4, 8), n(Re4, 2),
      // y otra vez, con el final resuelto en Do
      n(Mi4, 4), n(Mi4, 4), n(Fa4, 4), n(Sol4, 4),
      n(Sol4, 4), n(Fa4, 4), n(Mi4, 4), n(Re4, 4),
      n(Do4, 4), n(Do4, 4), n(Re4, 4), n(Mi4, 4),
      n(Re4, 4, { puntillo: true }), n(Do4, 8), n(Do4, 2),
    ],
    izquierda: [
      n([Do3, Sol3], 1),
      n([Si2, Sol3], 1),
      n([Do3, Sol3], 1),
      n([Sol2, Re3], 1),
      n([Do3, Sol3], 1),
      n([Si2, Sol3], 1),
      n([Do3, Mi3], 1),
      n([Sol2, Re3], 2), n([Do3, Sol3], 2),
    ],
  },

  {
    slug: "oda-a-la-alegria-en-sol",
    fuente: "/fuentes/oda-a-la-alegria-en-sol.mxl",
    titulo: "Oda a la alegría, entera y en Sol",
    compositor: "Beethoven",
    anio: "1824",
    compas: { numerador: 4, denominador: 4 },
    tonalidad: { tonica: 7, modo: "mayor" },
    bpm: 120,
    dificultad: 2,
    sobre:
      "El mismo tema de la otra Oda, pero completo: trae la vuelta del medio que la versión de ocho compases saltea, y está en Sol —con su fa sostenido en la armadura—. La izquierda ya no son dos acordes: son tríadas enteras y unos bajos que caminan solos. Compará las dos y se escucha qué le faltaba a la corta.",
    hasta: "Entera: el tema dos veces, la vuelta del medio y el cierre.",
    revisar:
      "Importada de un MusicXML sin pérdidas, así que las notas son las del archivo. El tempo del archivo dice 140; acá arranca en 120, que para leer alcanza y sobra.",
    derecha: [
      // El tema. En Sol arranca en Si, la tercera — igual que en Do arrancaba en Mi.
      n(Si4, 4), n(Si4, 4), n(Do5, 4), n(Re5, 4),
      n(Re5, 4), n(Do5, 4), n(Si4, 4), n(La4, 4),
      n(Sol4, 4), n(Sol4, 4), n(La4, 4), n(Si4, 4),
      n(Si4, 4, { puntillo: true }), n(La4, 8), n(La4, 2),
      n(Si4, 4), n(Si4, 4), n(Do5, 4), n(Re5, 4),
      n(Re5, 4), n(Do5, 4), n(Si4, 4), n(La4, 4),
      n(Sol4, 4), n(Sol4, 4), n(La4, 4), n(Si4, 4),
      n(La4, 4, { puntillo: true }), n(Sol4, 8), n(Sol4, 2),
      // La vuelta del medio, la que la versión corta no tiene.
      n(La4, 4), n(La4, 4), n(Si4, 4), n(Sol4, 4),
      n(La4, 4), n(Si4, 8), n(Do5, 8), n(Si4, 4), n(Sol4, 4),
      n(La4, 4), n(Si4, 8), n(Do5, 8), n(Si4, 4), n(La4, 4),
      n(Sol4, 4), n(La4, 4), n(Re4, 2),
      // Y el tema por última vez, cerrando en Sol.
      n(Si4, 4), n(Si4, 4), n(Do5, 4), n(Re5, 4),
      n(Re5, 4), n(Do5, 4), n(Si4, 4), n(La4, 4),
      n(Sol4, 4), n(Sol4, 4), n(La4, 4), n(Si4, 4),
      n(La4, 4, { puntillo: true }), n(Sol4, 8), n(Sol4, 2),
      n(Sol4, 1),
    ],
    izquierda: [
      // Tríadas de Sol y de Re con séptima, tenidas.
      n([Sol3, Si3, Re4], 1), n([Fas3, La3, Re4], 1), n([Sol3, Si3, Re4], 1),
      n([Sol3, Si3, Re4], 2), n([Fas3, La3, Re4], 2),
      n([Sol3, Si3, Re4], 1), n([Fas3, La3, Re4], 1), n([Sol3, Si3, Re4], 1),
      n([Fas3, La3, Re4], 2), n([Sol3, Si3, Re4], 2),
      // En la vuelta del medio el bajo baja hasta el Re grave y camina.
      n(Re2, 2), n([Re3, Sol3, Si3], 2),
      n(Re2, 2), n([Re3, Sol3, Si3], 2),
      n(Re2, 2), n([Re3, Sol3, Si3], 2),
      n(Dos3, 2), n([Re3, Fas3, La3], 2),
      n([Sol3, Si3, Re4], 1), n([Fas3, La3, Re4], 1), n([Sol3, Si3, Re4], 1),
      n([Fas3, La3, Re4], 2), n([Sol3, Si3, Re4], 2),
      n([Sol3, Si3, Re4], 1),
    ],
  },

  {
    slug: "preludio-en-do",
    titulo: "Preludio nº 1 en Do mayor",
    compositor: "Bach",
    anio: "1722",
    compas: { numerador: 4, denominador: 4 },
    tonalidad: { tonica: 0, modo: "mayor" },
    bpm: 66,
    dificultad: 2,
    sobre:
      "Cuatro compases y son exactamente lo que estás estudiando: cada uno es un acorde desarmado nota por nota, y lo único que pasa entre compás y compás es que una o dos notas se mueven. Es el enlace de acordes, escrito.",
    hasta: "Los primeros cuatro compases, de un preludio de treinta y cinco.",
    revisar:
      "Las alturas están chequeadas contra un MusicXML de la edición Breitkopf & Härtel de 1866 (la primera versión que escribimos acá estaba una octava abajo). El tenor va escrito en el pentagrama de arriba con las plicas para abajo, como en las ediciones; con qué mano conviene tocarlo es pregunta para el profe. Y termina cada mitad de compás en un silencio de semicorchea donde la edición lo liga hasta la barra: nuestras ligaduras todavía no suenan, y con el pedal es lo mismo.",
    // El acorde nunca suena en bloque: el bajo arranca, el tenor entra en la
    // segunda semicorchea y recién ahí corre el arpegio. El tenor va en el
    // pentagrama de arriba porque ahí lo escriben las ediciones — Mi4 y Re4
    // caen justo al pie de la clave de sol, y en el de abajo quedaban
    // amontonados cabeza contra cabeza con el bajo.
    derecha: [
      [
        ...repetir([silencio(8), n(Sol4, 16), n(Do5, 16), n(Mi5, 16), n(Sol4, 16), n(Do5, 16), n(Mi5, 16)], 2),
        ...repetir([silencio(8), n(La4, 16), n(Re5, 16), n(Fa5, 16), n(La4, 16), n(Re5, 16), n(Fa5, 16)], 2),
        ...repetir([silencio(8), n(Sol4, 16), n(Re5, 16), n(Fa5, 16), n(Sol4, 16), n(Re5, 16), n(Fa5, 16)], 2),
        ...repetir([silencio(8), n(Sol4, 16), n(Do5, 16), n(Mi5, 16), n(Sol4, 16), n(Do5, 16), n(Mi5, 16)], 2),
      ],
      [
        ...repetir([silencio(16), n(Mi4, 4, { puntillo: true }), silencio(16)], 2),
        ...repetir([silencio(16), n(Re4, 4, { puntillo: true }), silencio(16)], 2),
        ...repetir([silencio(16), n(Re4, 4, { puntillo: true }), silencio(16)], 2),
        ...repetir([silencio(16), n(Mi4, 4, { puntillo: true }), silencio(16)], 2),
      ],
    ],
    izquierda: [
      n(Do4, 2), n(Do4, 2), n(Do4, 2), n(Do4, 2),
      n(Si3, 2), n(Si3, 2),
      n(Do4, 2), n(Do4, 2),
    ],
  },
  {
    slug: "claro-de-luna",
    fuente: "/fuentes/claro-de-luna.mxl",
    titulo: "Claro de luna",
    compositor: "Beethoven",
    anio: "1801",
    compas: { numerador: 4, denominador: 4 },
    tonalidad: { tonica: 1, modo: "menor" },
    bpm: 54,
    dificultad: 4,
    sobre: 
      "El primer movimiento de la sonata Op. 27 nº 2, entero. La derecha hace dos cosas a la vez y por eso va en dos voces: abajo el arpegio de tresillos que no para nunca, arriba la melodía con su propio ritmo. Fijate cómo las plicas de una van para arriba y las de la otra para abajo — es lo que permite leerlas separadas aunque compartan el pentagrama.",
    revisar:
      "Importada de un MusicXML, con sus tresillos y sus dos voces. La izquierda del original llega a tener cuatro voces en algunos pasajes y sólo entran dos: se quedaron las que más notas tienen, y se perdieron 118 notas de las otras. Es la limitación que queda.",
    hasta: "El movimiento completo, sesenta y nueve compases.",
    derecha: [
      [
        n(56, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(57, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), n(62, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(57, 8, { irregular: TRESILLO }),
        n(62, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), n(60, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(60, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        silencio(2), silencio(4), n(68, 8, { puntillo: true }), n(68, 16),
        n(68, 2, { puntillo: true }), n(68, 8, { puntillo: true }), n(68, 16),
        n(68, 2), n(69, 2), n(68, 2), n(66, 4), n(71, 4), n(64, 4), silencio(4),
        silencio(2), silencio(2), silencio(4), n(67, 8, { puntillo: true }),
        n(67, 16), n(67, 2, { puntillo: true }), n(67, 8, { puntillo: true }),
        n(67, 16), n(67, 2, { puntillo: true }), n(66, 4), n(66, 2), n(67, 4),
        n(64, 4), n(66, 2), n(66, 2), n(59, 4), silencio(4), silencio(4), n(71, 4),
        n(72, 2, { puntillo: true }), n(70, 4), n(71, 2, { puntillo: true }),
        n(71, 4), n(72, 2, { puntillo: true }), n(70, 4), n(71, 2), n(71, 2),
        n(71, 2), n(69, 2), n(67, 2), n(66, 2), n(61, 2), n(61, 4), n(61, 4),
        silencio(4), silencio(4), silencio(4), n(73, 8, { puntillo: true }),
        n(73, 16), n(73, 2, { puntillo: true }), n(73, 8, { puntillo: true }),
        n(73, 16), n(73, 2), n(72, 4), n(73, 4), n(75, 2, { puntillo: true }),
        n(75, 4), n(76, 2), n(75, 4), n(73, 4), n(72, 8, { irregular: TRESILLO }),
        n(60, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(68, 4), n(69, 4), n(66, 4), silencio(8, { irregular: TRESILLO }),
        n(60, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        silencio(1, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(73, 4), n(76, 4), n(73, 4),
        silencio(8, { irregular: TRESILLO }), silencio(1, { irregular: TRESILLO }),
        silencio(4), silencio(4), n(60, 8, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(60, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(72, 8, { irregular: TRESILLO }),
        silencio(4), n(64, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(73, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(76, 8, { irregular: TRESILLO }),
        n(73, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(67, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(70, 8, { irregular: TRESILLO }),
        n(67, 8, { irregular: TRESILLO }), n(73, 8, { irregular: TRESILLO }),
        n(70, 8, { irregular: TRESILLO }), n(76, 8, { irregular: TRESILLO }),
        n(73, 8, { irregular: TRESILLO }), n(79, 8, { irregular: TRESILLO }),
        n(76, 8, { irregular: TRESILLO }), n(82, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(72, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(75, 8, { irregular: TRESILLO }),
        n(72, 8, { irregular: TRESILLO }), n(78, 8, { irregular: TRESILLO }),
        n(75, 8, { irregular: TRESILLO }), n(81, 8, { irregular: TRESILLO }),
        n(78, 8, { irregular: TRESILLO }), n(84, 8, { irregular: TRESILLO }),
        n(81, 8, { irregular: TRESILLO }), n(87, 8, { irregular: TRESILLO }),
        n(84, 8, { irregular: TRESILLO }), n(78, 8, { irregular: TRESILLO }),
        n(81, 8, { irregular: TRESILLO }), n(75, 8, { irregular: TRESILLO }),
        n(78, 8, { irregular: TRESILLO }), n(72, 8, { irregular: TRESILLO }),
        n(75, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(72, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(60, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), silencio(1, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), silencio(1), silencio(1), silencio(1),
        silencio(1), silencio(2), silencio(4), n(68, 8, { puntillo: true }),
        n(68, 16), n(68, 2, { puntillo: true }), n(68, 8, { puntillo: true }),
        n(68, 16), n(68, 2), n(69, 2), n(68, 2), n(66, 4), n(71, 4), n(64, 4),
        silencio(4), silencio(4), n(71, 8, { puntillo: true }), n(71, 16),
        n(71, 2, { puntillo: true }), n(71, 8, { puntillo: true }), n(71, 16),
        n(71, 2), n(72, 4), n(73, 4), n(75, 2), n(76, 2), n(74, 2), n(72, 2),
        n(73, 2, { puntillo: true }), n(73, 4), n(74, 2, { puntillo: true }),
        n(72, 4), n(73, 2, { puntillo: true }), n(73, 4),
        n(74, 2, { puntillo: true }), n(72, 4), n(73, 2), n(73, 2),
        n(71, 2, { puntillo: true }), n(71, 4), n(69, 4), n(69, 4), n(68, 4),
        n(68, 4), n(66, 2), n(68, 4), n(69, 4), n(68, 2), n(68, 2),
        silencio(2, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(73, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(76, 8, { irregular: TRESILLO }), n(73, 8, { irregular: TRESILLO }),
        n(80, 8, { irregular: TRESILLO }), n(76, 8, { irregular: TRESILLO }),
        n(73, 8, { irregular: TRESILLO }), n(72, 8, { irregular: TRESILLO }),
        n(75, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(72, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), silencio(2, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(73, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(76, 8, { irregular: TRESILLO }),
        n(73, 8, { irregular: TRESILLO }), n(80, 8, { irregular: TRESILLO }),
        n(76, 8, { irregular: TRESILLO }), n(73, 8, { irregular: TRESILLO }),
        n(72, 8, { irregular: TRESILLO }), n(75, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(72, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        silencio(2, { irregular: TRESILLO }), silencio(2),
        silencio(8, { irregular: TRESILLO }), silencio(2, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        silencio(2, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        silencio(2), silencio(2), n(61, 2), n(61, 1),
      ],
      [
        silencio(1), silencio(1), silencio(1), silencio(1),
        silencio(2, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(65, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(65, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(65, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(65, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(4), silencio(1), silencio(1),
        n(59, 8, { irregular: TRESILLO }), n(62, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(62, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(67, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(67, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(67, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(67, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(67, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(67, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(67, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(67, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(62, 8, { irregular: TRESILLO }),
        n(65, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(62, 8, { irregular: TRESILLO }), n(65, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(57, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        silencio(1), silencio(1), silencio(2, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(71, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(71, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(71, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(71, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(60, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(73, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(73, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(70, 8, { irregular: TRESILLO }),
        silencio(4), n(68, 8, { irregular: TRESILLO }),
        n(60, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(60, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(60, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        silencio(2, { irregular: TRESILLO }), n(60, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(60, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(60, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), silencio(4),
        n(73, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(76, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(73, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), silencio(1), silencio(1), silencio(1),
        silencio(1), silencio(1), silencio(1), silencio(1), silencio(1),
        silencio(1), silencio(1), silencio(1), silencio(2),
        silencio(8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(60, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(73, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(73, 8, { irregular: TRESILLO }),
        n(62, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(62, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(60, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(60, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(65, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(65, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(65, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(65, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(65, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(65, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(65, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(65, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(69, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(69, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(68, 8, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(68, 8, { irregular: TRESILLO }), n(57, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(66, 8, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(66, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        silencio(1), silencio(1), n(61, 4), silencio(1, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), silencio(1), silencio(1), silencio(1),
        silencio(1), silencio(1), silencio(1), silencio(1), silencio(1),
        silencio(1),
      ],
    ],
    izquierda: [
      [
        silencio(1), silencio(1), silencio(1), silencio(1),
        n(52, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        silencio(4, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        silencio(4, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        silencio(4, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        silencio(4, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        silencio(4, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        silencio(4, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        silencio(4, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        silencio(4, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        silencio(4, { irregular: TRESILLO }), n(57, 8, { irregular: TRESILLO }),
        silencio(4, { irregular: TRESILLO }), n(57, 8, { irregular: TRESILLO }),
        silencio(4, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(57, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(55, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(55, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(55, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(55, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(55, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(55, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(55, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(55, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(55, 8, { irregular: TRESILLO }),
        n(60, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(55, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(55, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(54, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(54, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(62, 8, { irregular: TRESILLO }),
        n(54, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(62, 8, { irregular: TRESILLO }), n(55, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(52, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(54, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(62, 8, { irregular: TRESILLO }),
        n(54, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(62, 8, { irregular: TRESILLO }), n(54, 8, { irregular: TRESILLO }),
        n(58, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(54, 8, { irregular: TRESILLO }), n(58, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), silencio(1), silencio(1), silencio(1),
        silencio(1), silencio(1), silencio(1), n(55, 8, { irregular: TRESILLO }),
        n(59, 8, { irregular: TRESILLO }), n(62, 8, { irregular: TRESILLO }),
        n(55, 8, { irregular: TRESILLO }), n(59, 8, { irregular: TRESILLO }),
        n(62, 8, { irregular: TRESILLO }), n(54, 8, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(54, 8, { irregular: TRESILLO }), n(57, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(49, 8, { irregular: TRESILLO }),
        n(54, 8, { irregular: TRESILLO }), n(57, 8, { irregular: TRESILLO }),
        n(49, 8, { irregular: TRESILLO }), n(54, 8, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), n(49, 8, { irregular: TRESILLO }),
        n(54, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(49, 8, { irregular: TRESILLO }), n(53, 8, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), n(54, 8, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        silencio(2), silencio(8, { irregular: TRESILLO }), silencio(1), silencio(1),
        silencio(1), silencio(1), silencio(1), silencio(4),
        n(56, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(54, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        silencio(1), silencio(4), n(61, 8, { irregular: TRESILLO }),
        n(52, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(52, 8, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(52, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        silencio(1), silencio(1), silencio(1), silencio(1), silencio(1),
        silencio(2), n(57, 8, { irregular: TRESILLO }),
        n(51, 4, { irregular: TRESILLO }),
        n(49, 4, { puntillo: true, irregular: TRESILLO }), n(48, 2), n(51, 4),
        n(49, 4), n(48, 2), n(50, 4), n(49, 4), n(48, 2), silencio(2), silencio(1),
        n(52, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), silencio(4, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), silencio(1, { irregular: TRESILLO }),
        silencio(4), silencio(1), silencio(1), silencio(1), silencio(1),
        silencio(1), silencio(1), silencio(1), silencio(1), silencio(1),
        silencio(1), silencio(1), n(54, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(54, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(57, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), n(56, 8, { irregular: TRESILLO }),
        n(61, 8, { irregular: TRESILLO }), n(64, 8, { irregular: TRESILLO }),
        n(56, 8, { irregular: TRESILLO }), n(61, 8, { irregular: TRESILLO }),
        n(64, 8, { irregular: TRESILLO }), n(54, 8, { irregular: TRESILLO }),
        n(60, 8, { irregular: TRESILLO }), n(63, 8, { irregular: TRESILLO }),
        n(54, 8, { irregular: TRESILLO }), n(60, 8, { irregular: TRESILLO }),
        n(63, 8, { irregular: TRESILLO }), silencio(1), silencio(1), silencio(1),
        silencio(1, { irregular: TRESILLO }), silencio(8, { irregular: TRESILLO }),
        n(60, 4), silencio(1), silencio(1, { irregular: TRESILLO }),
        silencio(8, { irregular: TRESILLO }), n(60, 4), silencio(1), silencio(1),
        silencio(2), n([52, 56], 2), n([52, 56], 1),
      ],
      [
        n([37, 49], 1), n([35, 47], 1), n([33, 45], 2), n([30, 42], 2),
        n([32, 44], 2), n([32, 44], 2), n([37, 44, 49], 1), n([36, 44, 48], 1),
        n([37, 49], 2), n([30, 42], 2), n([35, 47], 2), n([35, 47], 2),
        n([40, 52], 1), n([40, 52], 1), n([38, 50], 1), n([36, 48], 4),
        n([35, 47], 4), n([34, 46], 2), n([35, 47], 2), n(40, 4), n(43, 4),
        n(42, 2), n([30, 42], 2), n([35, 47], 1), n([35, 47], 4), n([40, 52], 4),
        n([43, 55], 4), n([40, 52], 4), n([35, 47], 1), n([35, 47], 4),
        n([40, 52], 4), n([43, 55], 4), n([40, 52], 4), n([35, 47], 2),
        n([32, 44], 2), n([29, 41], 2), n([30, 42], 2), n([35, 47], 2),
        n([36, 48], 2), n(37, 2), n(37, 2), n([30, 37, 42], 1), n([41, 49, 53], 1),
        n([42, 54], 2), n([39, 51], 4), n([37, 49], 4),
        n([36, 44, 48], 2, { puntillo: true }), n([36, 44, 48], 4),
        n([37, 44, 49], 2), n([30, 42], 4), n([31, 43], 4), n([32, 44], 1),
        n([32, 44], 1), n([32, 44], 1), n([32, 44], 1), n([32, 44], 1),
        n([32, 44], 1), n([32, 44], 1), n([32, 44], 1), n([32, 44], 1),
        n([32, 44], 1), n([32, 44], 1), n([32, 44], 1), n([32, 44], 2),
        n([33, 45], 2), n([30, 42], 2), n([32, 44], 2), n([37, 44, 49], 1),
        n([36, 44, 48], 1), n([37, 49], 2), n([30, 42], 2), n([35, 47], 2),
        n([35, 47], 2), n([40, 52], 1), n([39, 51], 1), n([40, 52], 2),
        n([39, 51], 4), n([37, 49], 4), n([36, 44, 48], 2), n([37, 44, 49], 2),
        n([30, 42], 2), n([32, 44], 2), n([37, 49], 1), n([37, 49], 4),
        n([42, 54], 4), n([45, 57], 4), n([42, 54], 4), n([37, 49], 1),
        n([37, 49], 4), n([42, 54], 4), n([45, 57], 4), n([42, 54], 4),
        n([37, 49], 2), n([30, 42], 2), n([39, 51], 2, { puntillo: true }),
        n([40, 52], 4), n([37, 49], 4), n([39, 51], 4), n([36, 48], 4),
        n([37, 49], 4), n([33, 45], 2), n([32, 44], 4), n([30, 42], 4),
        n([32, 44], 2), n([32, 44], 2), n(44, 2, { puntillo: true }),
        n(44, 8, { puntillo: true }), n(44, 16), n(44, 2, { puntillo: true }),
        n(44, 8, { puntillo: true }), n(44, 16), n(44, 2, { puntillo: true }),
        n(44, 8, { puntillo: true }), n(44, 16), n(44, 2, { puntillo: true }),
        n(44, 8, { puntillo: true }), n(44, 16), n(44, 2, { puntillo: true }),
        n(44, 8, { puntillo: true }), n(44, 16), n(44, 2, { puntillo: true }),
        n(44, 8, { puntillo: true }), n(44, 16), n(44, 2), n(49, 2), n(44, 2),
        n(44, 8, { irregular: TRESILLO }), n(49, 8, { irregular: TRESILLO }),
        n(44, 8, { irregular: TRESILLO }), n(40, 8, { irregular: TRESILLO }),
        n(44, 8, { irregular: TRESILLO }), n(40, 8, { irregular: TRESILLO }),
        n(37, 2), n([37, 44, 49], 2), n([37, 44, 49], 1),
      ],
    ],
  },

  {
    slug: "canon-en-re",
    fuente: "/fuentes/canon-en-re.mxl",
    titulo: "Canon en Re",
    compositor: "Pachelbel",
    anio: "c. 1690",
    compas: { numerador: 4, denominador: 4 },
    tonalidad: { tonica: 2, modo: "mayor" },
    bpm: 50,
    dificultad: 2,
    sobre: 
      "La izquierda es el bajo más famoso de la historia: ocho notas que dan vueltas y sobre las que se escribieron miles de canciones. Se puede estudiar sola —son las mismas ocho cada dos compases— y la derecha entra recién en el quinto.",
    revisar:
      "Importada de un MusicXML, así que las alturas y las figuras salen del archivo y no de nuestra memoria.",
    hasta: "Los primeros ocho compases de un arreglo fácil.",
    derecha: [
      silencio(1), silencio(1), silencio(1), silencio(1), n(78, 2), n(76, 2),
      n(74, 2), n(73, 2), n(71, 2), n(69, 2), n(71, 2), n(73, 2),
    ],
    izquierda: [
      n(50, 8), n(54, 8), n(57, 8), n(62, 8), n(45, 8), n(49, 8), n(52, 8),
      n(57, 8), n(47, 8), n(50, 8), n(54, 8), n(59, 8), n(42, 8), n(45, 8),
      n(49, 8), n(54, 8), n(43, 8), n(47, 8), n(50, 8), n(55, 8), n(38, 8),
      n(42, 8), n(45, 8), n(50, 8), n(43, 8), n(47, 8), n(50, 8), n(55, 8),
      n(45, 8), n(49, 8), n(52, 8), n(57, 8), n(50, 8), n(54, 8), n(57, 8),
      n(62, 8), n(45, 8), n(49, 8), n(52, 8), n(57, 8), n(47, 8), n(50, 8),
      n(54, 8), n(59, 8), n(42, 8), n(45, 8), n(49, 8), n(54, 8), n(43, 8),
      n(47, 8), n(50, 8), n(55, 8), n(38, 8), n(42, 8), n(45, 8), n(50, 8),
      n(43, 8), n(47, 8), n(50, 8), n(55, 8), n(45, 8), n(49, 8), n(52, 8),
      n(57, 8),
    ],
  },

  {
    slug: "minueto-en-sol",
    fuente: "/fuentes/minueto-en-sol.mxl",
    titulo: "Minueto en Sol",
    compositor: "Christian Petzold",
    anio: "c. 1725",
    compas: { numerador: 3, denominador: 4 },
    tonalidad: { tonica: 7, modo: "mayor" },
    bpm: 80,
    dificultad: 2,
    sobre: 
      "El primer minueto que estudia todo el mundo. Estuvo doscientos años atribuido a Bach porque apareció en un cuaderno suyo, y resultó ser de Petzold. Una mano por vez y sale: la derecha es melodía pura y la izquierda casi no se mueve.",
    revisar:
      "Importada de un MusicXML.",
    hasta: "Los primeros dieciséis compases, o sea la primera parte.",
    derecha: [
      n(74, 4), n(67, 8), n(69, 8), n(71, 8), n(72, 8), n(74, 4), n(67, 4),
      n(67, 4), n(76, 4), n(72, 8), n(74, 8), n(76, 8), n(78, 8), n(79, 4),
      n(67, 4), n(67, 4), n(72, 4), n(74, 8), n(72, 8), n(71, 8), n(69, 8),
      n(71, 4), n(72, 8), n(71, 8), n(69, 8), n(67, 8), n(66, 4), n(67, 8),
      n(69, 8), n(71, 8), n(67, 8), n(71, 4), n(69, 2), n(74, 4), n(67, 8),
      n(69, 8), n(71, 8), n(72, 8), n(74, 4), n(67, 4), n(67, 4), n(76, 4),
      n(72, 8), n(74, 8), n(76, 8), n(78, 8), n(79, 4), n(67, 4), n(67, 4),
      n(72, 4), n(74, 8), n(72, 8), n(71, 8), n(69, 8), n(71, 4), n(72, 8),
      n(71, 8), n(69, 8), n(67, 8), n(69, 4), n(71, 8), n(69, 8), n(67, 8),
      n(66, 8), n(67, 2, { puntillo: true }),
    ],
    izquierda: [
      n([55, 59, 62], 2), n(57, 4), n(59, 2, { puntillo: true }),
      n(60, 2, { puntillo: true }), n(59, 2, { puntillo: true }),
      n(57, 2, { puntillo: true }), n(55, 2, { puntillo: true }), n(62, 4),
      n(59, 4), n(55, 4), n(62, 4), n(50, 8), n(60, 8), n(59, 8), n(57, 8),
      n(59, 2), n(57, 4), n(55, 4), n(59, 4), n(55, 4),
      n(60, 2, { puntillo: true }), n(59, 4), n(60, 8), n(59, 8), n(57, 8),
      n(55, 8), n(57, 2), n(54, 4), n(55, 2), n(59, 4), n(60, 4), n(62, 4),
      n(50, 4), n(55, 2), n(43, 4),
    ],
  },

  {
    slug: "para-elisa",
    fuente: "/fuentes/para-elisa.mxl",
    titulo: "Para Elisa",
    compositor: "Beethoven",
    anio: "1810",
    compas: { numerador: 3, denominador: 8 },
    tonalidad: { tonica: 9, modo: "menor" },
    bpm: 120,
    dificultad: 3,
    sobre: 
      "El arranque que todo el mundo tiene en la cabeza. Fijate el compás: 3/8, tres corcheas por compás, así que el pulso va bastante más rápido de lo que el número sugiere.",
    revisar:
      "Importada de un MusicXML. Arranca con anacrusa —dos semicorcheas antes del primer compás— y nuestro modelo no tiene compases incompletos, así que se rellenó con silencios: los números de compás quedan corridos uno respecto de la edición.",
    hasta: "Los primeros dieciséis compases.",
    derecha: [
      silencio(4), n(76, 16), n(75, 16), n(76, 16), n(75, 16), n(76, 16),
      n(71, 16), n(74, 16), n(72, 16), n(69, 8), silencio(16), n(60, 16),
      n(64, 16), n(69, 16), n(71, 8), silencio(16), n(64, 16), n(68, 16),
      n(71, 16), n(72, 8), silencio(16), n(64, 16), n(76, 16), n(75, 16),
      n(76, 16), n(75, 16), n(76, 16), n(71, 16), n(74, 16), n(72, 16), n(69, 8),
      silencio(16), n(60, 16), n(64, 16), n(69, 16), n(71, 8), silencio(16),
      n(64, 16), n(72, 16), n(71, 16), n(69, 4), silencio(8), n(69, 8),
      silencio(16), n(71, 16), n(72, 16), n(74, 16), n(76, 8, { puntillo: true }),
      n(67, 16), n(77, 16), n(76, 16), n(74, 8, { puntillo: true }), n(65, 16),
      n(76, 16), n(74, 16), n(72, 8, { puntillo: true }), n(64, 16), n(74, 16),
      n(72, 16), n(71, 8), silencio(16), n(64, 16), n(76, 16), silencio(16),
      silencio(16), n(76, 16), n(88, 16), silencio(16), silencio(16), n(75, 16),
      n(76, 16), silencio(16), silencio(16), n(75, 16), n(76, 16), n(75, 16),
      n(76, 16), n(75, 16), n(76, 16), n(71, 16), n(74, 16), n(72, 16),
    ],
    izquierda: [
      silencio(4), silencio(8), silencio(4, { puntillo: true }), n(45, 16),
      n(52, 16), n(57, 16), silencio(16), silencio(8), n(40, 16), n(52, 16),
      n(56, 16), silencio(16), silencio(8), n(45, 16), n(52, 16), n(57, 16),
      silencio(16), silencio(8), silencio(4, { puntillo: true }), n(45, 16),
      n(52, 16), n(57, 16), silencio(16), silencio(8), n(40, 16), n(52, 16),
      n(56, 16), silencio(16), silencio(8), n(45, 16), n(52, 16), n(57, 16),
      silencio(16), silencio(8), n(45, 16), n(52, 16), n(57, 16), silencio(16),
      silencio(8), n(48, 16), n(55, 16), n(60, 16), silencio(16), silencio(8),
      n(43, 16), n(55, 16), n(59, 16), silencio(16), silencio(8), n(45, 16),
      n(52, 16), n(57, 16), silencio(16), silencio(8), n(40, 16), n(52, 16),
      n(64, 16), silencio(16), silencio(16), n(64, 16), n(76, 16), silencio(16),
      silencio(16), n(75, 16), n(76, 16), silencio(16), silencio(16), n(75, 16),
      n(76, 16), silencio(16), silencio(8), silencio(4, { puntillo: true }),
    ],
  },
];

/** Repite un grupo de eventos, que es como está escrita la música de verdad. */
function repetir(grupo: Evento[], veces: number): Evento[] {
  return Array.from({ length: veces }, () => grupo.map((e) => ({ ...e }))).flat();
}

export function piezaPorSlug(slug: string): Pieza | undefined {
  return PIEZAS.find((p) => p.slug === slug);
}

